async function openContent(id){let [cs,tr,vs,ss]=await Promise.all([db(`contents?id=eq.${id}&select=*`),db(`transcripts?content_id=eq.${id}&select=*`),db(`social_variants?content_id=eq.${id}&select=*`),db(`schedules?content_id=eq.${id}&select=*&order=scheduled_for.desc`)]),c=cs[0];if(!c)return;currentContent=id;$('#dlgTitle').textContent=c.title;let vmap=Object.fromEntries(vs.map(v=>[v.platform,v])),mediaState=c.status==='IN_ELABORAZIONE'?'<p class="warn"><b>Upload incompleto o in verifica.</b> Il riferimento è stato conservato per il recupero. Se il trasferimento non è terminato, puoi eliminare questo contenuto e ricaricarlo.</p>':c.storage_path?'<p>✓ Video presente nello storage privato</p>':'<p class=danger>Video non presente</p>';$('#dlgBody').innerHTML=`<p><span class="status ${c.status}">${c.status}</span> ${esc(c.category||'')}</p><p class=hint>${esc(c.notes||'')}</p>${mediaState}<hr><h3>Trascrizione</h3><textarea id=transcript rows=7 placeholder="Incolla o modifica qui la trascrizione">${esc(tr[0]?.corrected_text||'')}</textarea><div class=actions><button id=saveTranscript class=ghost>Salva trascrizione</button><button id=aiInfo class=ghost>Genera con IA</button></div><hr><h3>Caption social</h3><div id=variantTabs class=tabs>${['instagram','facebook','tiktok','youtube','linkedin'].map((p,i)=>`<button data-p="${p}" class="${i?'':'active'}">${p}</button>`).join('')}</div><div id=variantBox></div><hr><div class=actions><button id=approveContent>Approva contenuto</button><input id=sched type=datetime-local style="max-width:240px"><button id=schedule class=ghost>Programma</button><button id=reopen class=ghost>Riapri</button><button id=deleteContent class=ghost>Elimina</button></div><div class=stack>${ss.map(s=>`<div class=item><div><b>${s.platform}</b><p>${fmt(s.scheduled_for)}</p></div><span class="status ${s.status}">${s.status}</span></div>`).join('')}</div>`;
 let render=p=>{let v=vmap[p]||{platform:p,hook:'',cta:'',hashtags:[],variants:{},status:'DA_APPROVARE'},txt=p==='youtube'?(v.variants?.description||''):(v.variants?.medium||v.variants?.short||'');$('#variantBox').innerHTML=`<label>Testo<textarea id=vText rows=8>${esc(txt)}</textarea></label><div class=row><label>Hook<input id=vHook value="${esc(v.hook||'')}"></label><label>CTA<input id=vCta value="${esc(v.cta||'')}"></label></div><label>Hashtag / tag<input id=vTags value="${esc((v.hashtags||v.variants?.tags||[]).join(' '))}"></label><div class=actions><button id=vSave class=ghost>Salva</button><button id=vApprove>Approva caption</button><span class="status ${v.status}">${v.status}</span></div>`;$('#vSave').onclick=()=>saveVariant(p,false);$('#vApprove').onclick=()=>saveVariant(p,true)}
 async function saveVariant(p,approve){let old=vmap[p]||{},tags=$('#vTags').value.split(/\s+/).filter(Boolean),body={owner_id:S.user.id,content_id:id,platform:p,hook:$('#vHook').value,cta:$('#vCta').value,hashtags:tags,variants:p==='youtube'?{...(old.variants||{}),description:$('#vText').value,tags}:{...(old.variants||{}),medium:$('#vText').value},status:approve?'APPROVATO':'DA_APPROVARE',approved_at:approve?new Date().toISOString():null};let r=await db('social_variants?on_conflict=content_id,platform',{method:'POST',body,prefer:'resolution=merge-duplicates,return=representation'});vmap[p]=r[0]||body;toast(approve?'Caption approvata':'Caption salvata');render(p)}
 $$('#variantTabs button').forEach(b=>b.onclick=()=>{$$('#variantTabs button').forEach(x=>x.classList.toggle('active',x===b));render(b.dataset.p)});render('instagram');
 $('#saveTranscript').onclick=async()=>{let text=$('#transcript').value;await db('transcripts?on_conflict=content_id',{method:'POST',body:{owner_id:S.user.id,content_id:id,original_text:tr[0]?.original_text||text,corrected_text:text,language:'it'},prefer:'resolution=merge-duplicates,return=representation'});toast('Trascrizione salvata')};
 $('#aiInfo').onclick=()=>toast('Generazione IA non ancora collegata: nessun testo viene inventato o simulato.',true);
 $('#approveContent').onclick=async()=>{try{await db('rpc/approve_content',{method:'POST',body:{p_content_id:id}});toast('Contenuto approvato');await openContent(id);await all()}catch(e){toast(e.message,true)}};
 $('#schedule').onclick=async()=>{try{let d=$('#sched').value;if(!d||new Date(d)<=new Date())throw Error('Scegli una data futura');await db('rpc/schedule_content',{method:'POST',body:{p_content_id:id,p_when:new Date(d).toISOString()}});toast('Programmazione salvata');await openContent(id);await all()}catch(e){toast(e.message,true)}};
 $('#reopen').onclick=async()=>{await db('rpc/reopen_content',{method:'POST',body:{p_content_id:id}});toast('Contenuto riaperto');await openContent(id);await all()};
 $('#deleteContent').onclick=async()=>{if(!confirm('Eliminare contenuto e tutti i file collegati?'))return;let btn=$('#deleteContent');btn.disabled=true;try{let versions=await db(`media_versions?content_id=eq.${id}&select=storage_path`),objects=[['marta-content-originals',c.storage_path],['marta-content-derived',c.audio_storage_path],['marta-content-derived',c.publish_storage_path],...versions.map(v=>['marta-content-derived',v.storage_path])],seen=new Set;for(const [bucket,path] of objects){if(!path)continue;let k=bucket+'|'+path;if(seen.has(k))continue;seen.add(k);await martaDeleteStorageObject(bucket,path)}try{await db(`contents?id=eq.${id}`,{method:'DELETE'})}catch(err){try{await db(`contents?id=eq.${id}`,{method:'PATCH',body:{storage_path:null,audio_storage_path:null,publish_storage_path:null,status:'ERRORE'}})}catch{}throw err}$('#dlg').close();toast('Contenuto e file eliminati');await all()}catch(e){toast('Eliminazione non completata: '+e.message,true);btn.disabled=false}};
 if(!$('#dlg').open)$('#dlg').showModal()
}
async function calendar(){let st=$('#calStatus').value,q='schedules?select=*&order=scheduled_for.asc&limit=300';if(st)q+='&status=eq.'+st;let s=await db(q),c=await db('contents?select=id,title'),m=Object.fromEntries(c.map(x=>[x.id,x.title]));$('#calendarList').innerHTML=s.length?s.map(x=>`<div class=item><div><b>${esc(m[x.content_id]||'Contenuto')}</b><p>${x.platform} · ${fmt(x.scheduled_for)}</p></div><span class="status ${x.status}">${x.status}</span></div>`).join(''):'<p class=hint>Nessuna programmazione.</p>'}
async function autopilot(){let a=(await db('autopilot_settings?select=*'))[0];if(!a)return;$('#autoEnabled').checked=a.enabled;$('#autoPosts').value=a.posts_per_day;$('#autoSlot1').value=(a.slots?.[0]||'09:00').slice(0,5);$('#autoSlot2').value=(a.slots?.[1]||'18:00').slice(0,5);$('#autoState').textContent=a.enabled?'Autopilot attivo, sempre con approvazione obbligatoria.':'Autopilot disattivato.'}
async function leads(){let l=await db('leads?select=*&order=created_at.desc&limit=100');$('#leadList').innerHTML=l.length?l.map(x=>`<div class=item><div><b>${esc(x.name||'Lead')}</b><p>${esc(x.contact||'')} · ${esc(x.source||'')} · ${esc(x.request||'')}</p></div><select class=leadSt data-id="${x.id}" style="max-width:150px"><option ${x.status==='NUOVO'?'selected':''}>NUOVO</option><option ${x.status==='CONTATTATO'?'selected':''}>CONTATTATO</option><option ${x.status==='APPUNTAMENTO'?'selected':''}>APPUNTAMENTO</option><option ${x.status==='CLIENTE'?'selected':''}>CLIENTE</option><option ${x.status==='PERSO'?'selected':''}>PERSO</option></select></div>`).join(''):'<p class=hint>Nessun lead.</p>';$$('.leadSt').forEach(e=>e.onchange=async()=>{await db(`leads?id=eq.${e.dataset.id}`,{method:'PATCH',body:{status:e.value,acquired:e.value==='CLIENTE'}});toast('Lead aggiornato');await dash()})}
async function analytics(){let [c,l,s]=await Promise.all([db('contents?select=id'),db('leads?select=status,value'),db('schedules?select=status')]),clienti=l.filter(x=>x.status==='CLIENTE');$('#analyticsCards').innerHTML=[['Contenuti',c.length],['Lead',l.length],['Clienti',clienti.length],['Pubblicati',s.filter(x=>x.status==='PUBBLICATO').length]].map(x=>`<div class=card><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
async function integrations(){let i=await db('integrations?select=*&order=platform');$('#integrationList').innerHTML=i.map(x=>`<div class=integration><div><b>${x.platform}</b><p class=hint>${x.enabled?'OAuth collegato':'Da collegare con autorizzazione ufficiale'}</p></div><span class="status ${x.enabled?'APPROVATO':''}">${x.enabled?'COLLEGATO':'DA COLLEGARE'}</span></div>`).join('')}
async function costs(){let c=await db('service_costs?select=*&order=created_at.desc');$('#costList').innerHTML=c.length?c.map(x=>`<div class=item><div><b>${esc(x.service)}</b><p>${esc(x.provider||'')} · € ${Number(x.cost||0).toFixed(2)}</p></div></div>`).join(''):'<p class=hint>Nessun costo registrato. Struttura attuale: piano Supabase Free.</p>'}
async function settings(){let [e,p]=await Promise.all([db('editorial_profiles?select=*'),db('profiles?select=*')]);e=e[0]||{};p=p[0]||{};$('#setName').value=e.name||'Marta Ruffino';$('#setVoice').value=e.voice||'';$('#setForbidden').value=e.forbidden_claims||'';$('#setSite').value=p.site_url||''}
async function all(){let jobs=[dash(),contents(),calendar(),autopilot(),leads(),analytics(),integrations(),costs(),settings()];let r=await Promise.allSettled(jobs),bad=r.find(x=>x.status==='rejected');if(bad)toast(bad.reason.message,true)}
