const SB_URL='https://nqnmlsmeiynxbdojeyjt.supabase.co';const SB_KEY='sb_publishable_Clz5qPTkTtvwV0rqWTcfMQ_sCDSRgnu';const sb=supabase.createClient(SB_URL,SB_KEY);let session=null;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],today=()=>new Date().toISOString().slice(0,10),rid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+''+Math.random();
async function rows(c){if(!session)return[];let {data,error}=await sb.from('f1_records').select('*').eq('collection',c).eq('deleted',false);if(error)throw error;return data||[]}
async function save(c,p,id=rid()){if(!session)throw Error('Login richiesto');let row={owner_id:session.user.id,collection:c,record_id:id,payload:p,updated_at:new Date().toISOString(),deleted:false};let {error}=await sb.from('f1_records').upsert(row,{onConflict:'owner_id,collection,record_id'});if(error)throw error}
async function getSettings(){let r=await rows('settings'),x=r.find(z=>z.record_id==='funnel');return x?.payload||{goalType:'Fatturato',G:60000,P:3000,V:80,I:33.33,A:50,N:5,R:65,D:220,RP:10}}
function calc(s){let p=+s.P||1,g=+s.G||0,v=(+s.V||1)/100,i=(+s.I||1)/100,a=(+s.A||1)/100,n=(+s.N||1)/100,r=(+s.R||1)/100,d=+s.D||1;let sales=g/p,mand=sales/v,appt=mand/i,news=appt/a,conv=news/n,att=conv/r;return{sales,mand,appt,news,conv,att,dayAtt:Math.ceil(att/d),dayConv:Math.ceil(conv/d),dayNews:Math.ceil(news/d)}}
function loginBox(){document.body.insertAdjacentHTML('beforeend',`<dialog id="dlg" open><form method="dialog" class="card" style="position:fixed;inset:15% 6%;max-width:420px;margin:auto;height:max-content"><h2>F1 OS Companion</h2><label class="field"><span>Email</span><input id="em" type="email"></label><label class="field"><span>Password</span><input id="pw" type="password"></label><p id="msg" class="status">Accedi o crea un account.</p><div class="two"><button type="button" id="li" class="btn primary">ACCEDI</button><button type="button" id="su" class="btn ghost">CREA ACCOUNT</button></div><button class="btn ghost full">CHIUDI</button></form></dialog>`);$('#li').onclick=()=>auth(false);$('#su').onclick=()=>auth(true)}
async function auth(signup){let email=$('#em').value.trim(),password=$('#pw').value;let res=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(res.error){$('#msg').textContent=res.error.message;return}if(signup&&!res.data.session){$('#msg').textContent='Account creato. Controlla la mail di conferma.';return}session=res.data.session;$('#dlg')?.remove();render()}
async function increment(collection){if(!session)return loginBox();await save(collection,{date:today(),created_at:new Date().toISOString()});await refreshToday()}
async function refreshToday(){if(!session){['a1','a2','a3','a4'].forEach(x=>$('#'+x).textContent='—');return}let s=await getSettings(),c=calc(s),[at,co,ne,rp]=await Promise.all(['attempts','conversations','news','roleplay'].map(rows));let count=(arr)=>arr.filter(x=>(x.payload?.date||'')===today()).length;let vals=[[count(at),c.dayAtt,'a1','b1'],[count(co),c.dayConv,'a2','b2'],[count(ne),c.dayNews,'a3','b3'],[count(rp),+s.RP||10,'a4','b4']];for(let [v,t,a,b] of vals){$('#'+a).textContent=`${v} / ${t}`;$('#'+b).style.width=Math.min(100,t?100*v/t:0)+'%'}$('#headline').textContent=`${c.dayAtt} tentativi · ${c.dayConv} conversazioni · ${c.dayNews} notizie`;$('#formula').textContent=`Calcolato dal tuo funnel annuale (${s.goalType})`}
async function loadFunnel(){if(!session)return;let s=await getSettings();for(let k of ['goalType','G','P','V','I','A','N','R','D','RP'])$('#'+k).value=s[k];renderCalc(s)}
function renderCalc(s){let c=calc(s);$('#calc').innerHTML=`Vendite: <b>${Math.ceil(c.sales)}</b><br>Incarichi: <b>${Math.ceil(c.mand)}</b><br>Appuntamenti: <b>${Math.ceil(c.appt)}</b><br>Notizie: <b>${Math.ceil(c.news)}</b><br>Conversazioni: <b>${Math.ceil(c.conv)}</b><br>Tentativi: <b>${Math.ceil(c.att)}</b><hr>OGNI GIORNO: <b>${c.dayAtt} tentativi · ${c.dayConv} conversazioni · ${c.dayNews} notizie</b>`}
async function saveSettings(){if(!session)return loginBox();let s={};for(let k of ['goalType','G','P','V','I','A','N','R','D','RP'])s[k]=$('#'+k).value;await save('settings',s,'funnel');renderCalc(s);await refreshToday()}
function nav(n){$$('.screen').forEach(x=>x.classList.toggle('on',x.dataset.screen===n));$('#title').textContent=n==='today'?'OGGI':n.toUpperCase();if(n==='funnel')loadFunnel()}
async function render(){if(session){$('#acct').textContent=session.user.email;$('#cloudState').textContent='Connesso come '+session.user.email;$('#logout').style.display='block'}else{$('#acct').textContent='LOGIN';$('#cloudState').textContent='Non autenticato';$('#logout').style.display='none'}await refreshToday()}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$$('[data-inc]').forEach(b=>b.onclick=()=>increment(b.dataset.inc));$('#acct').onclick=()=>session?nav('cloud'):loginBox();$('#saveSettings').onclick=saveSettings;$('#logout').onclick=async()=>{await sb.auth.signOut();session=null;render()};(async()=>{let {data}=await sb.auth.getSession();session=data.session;await render();sb.auth.onAuthStateChange((_e,s)=>{session=s;render()});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})})();