const SB_URL='https://nqnmlsmeiynxbdojeyjt.supabase.co';const SB_KEY='sb_publishable_Clz5qPTkTtvwV0rqWTcfMQ_sCDSRgnu';const sb=supabase.createClient(SB_URL,SB_KEY);let session=null;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],today=()=>new Date().toISOString().slice(0,10),rid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+''+Math.random();
async function rows(c){if(!session)return[];let {data,error}=await sb.from('f1_records').select('*').eq('collection',c).eq('deleted',false).order('updated_at',{ascending:false});if(error)throw error;return data||[]}
async function save(c,p,id=rid()){if(!session)throw Error('Login richiesto');let row={owner_id:session.user.id,collection:c,record_id:id,payload:p,updated_at:new Date().toISOString(),deleted:false};let {error}=await sb.from('f1_records').upsert(row,{onConflict:'owner_id,collection,record_id'});if(error)throw error}
async function getSettings(){let r=await rows('settings'),x=r.find(z=>z.record_id==='funnel');return x?.payload||{goalType:'Fatturato',G:60000,P:3000,V:80,I:33.33,A:50,N:5,R:65,D:220}}
function calc(s){let p=+s.P||1,g=+s.G||0,v=(+s.V||1)/100,i=(+s.I||1)/100,a=(+s.A||1)/100,n=(+s.N||1)/100,r=(+s.R||1)/100,d=+s.D||1;let sales=g/p,mand=sales/v,appt=mand/i,news=appt/a,conv=news/n,att=conv/r;return{sales,mand,appt,news,conv,att,dayAtt:Math.ceil(att/d),dayConv:Math.ceil(conv/d),dayNews:Math.ceil(news/d),dayAppt:Math.ceil(appt/d)}}
function loginBox(){document.body.insertAdjacentHTML('beforeend',`<dialog id="dlg" open><form method="dialog" class="card" style="position:fixed;inset:15% 6%;max-width:420px;margin:auto;height:max-content"><h2>F1 OS Companion</h2><label>Email<input id="em" style="width:100%;padding:12px;margin:8px 0" type="email"></label><label>Password<input id="pw" style="width:100%;padding:12px;margin:8px 0" type="password"></label><p id="msg" class="status">Accedi con lo stesso account usato sul PC.</p><div class="two"><button type="button" id="li" class="btn primary">ACCEDI</button><button type="button" id="su" class="btn ghost">CREA ACCOUNT</button></div><button class="btn ghost full">CHIUDI</button></form></dialog>`);$('#li').onclick=()=>auth(false);$('#su').onclick=()=>auth(true)}
async function auth(signup){let email=$('#em').value.trim(),password=$('#pw').value;let res=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(res.error){$('#msg').textContent=res.error.message;return}if(signup&&!res.data.session){$('#msg').textContent='Account creato. Controlla la mail di conferma.';return}session=res.data.session;$('#dlg')?.remove();render()}
async function increment(collection){if(!session)return loginBox();await save(collection,{date:today(),created_at:new Date().toISOString(),source:'smartphone'});await refreshToday();if(collection==='appointments')await refreshAgenda()}
function cnt(arr){return arr.filter(x=>(x.payload?.date||x.payload?.created_at||'').slice(0,10)===today()).length}
async function refreshToday(){if(!session){['a1','a2','a3','a4'].forEach(x=>$('#'+x).textContent='—');$('#nextAction').textContent='';return}let s=await getSettings(),c=calc(s),[at,co,ne,ap]=await Promise.all(['attempts','conversations','news','appointments'].map(rows));let vals=[[cnt(at),c.dayAtt,'a1','b1'],[cnt(co),c.dayConv,'a2','b2'],[cnt(ne),c.dayNews,'a3','b3'],[cnt(ap),c.dayAppt,'a4','b4']];for(let [v,t,a,b] of vals){$('#'+a).textContent=`${v} / ${t}`;$('#'+b).style.width=Math.min(100,t?100*v/t:0)+'%'}let remA=Math.max(0,c.dayAtt-cnt(at)),remC=Math.max(0,c.dayConv-cnt(co)),remN=Math.max(0,c.dayNews-cnt(ne)),remP=Math.max(0,c.dayAppt-cnt(ap));$('#headline').textContent=`${c.dayAtt} tentativi · ${c.dayConv} conversazioni · ${c.dayNews} notizie`;let msg='Obiettivo giornaliero completato.';if(remN>0)msg=`Prossima azione: continua la prospezione. Mancano ${remN} notizie, ${remC} conversazioni e ${remA} tentativi.`;else if(remP>0)msg=`Prossima azione: sviluppa le notizie aperte. Manca ${remP} appuntamento.`;$('#nextAction').innerHTML=`<p><b>${msg}</b></p>`;$('#formula').textContent=`Obiettivi sincronizzati dal Funnel Engine del PC · ${s.goalType}`}
async function refreshAgenda(){if(!session)return;let [aps,cs]=await Promise.all([rows('appointments'),rows('contacts')]);let todays=aps.filter(x=>(x.payload?.date||'').slice(0,10)===today());$('#agenda').innerHTML=todays.length?todays.map(x=>`<div class="item"><b>${x.payload?.time||'Appuntamento'}</b><div>${x.payload?.person||x.payload?.name||''}</div><small>${x.payload?.note||''}</small></div>`).join(''):'<p class="status">Nessun appuntamento registrato per oggi.</p>';let f=cs.filter(x=>(x.payload?.follow||x.payload?.follow_up||'').slice(0,10)===today());$('#followups').innerHTML=f.length?f.map(x=>`<div class="item"><b>${x.payload?.first||''} ${x.payload?.last||''}</b><div>${x.payload?.street||''} · ${x.payload?.phone||''}</div></div>`).join(''):'<p class="status">Nessun follow-up con data odierna.</p>'}
async function refreshCRM(){if(!session)return;let c=await rows('contacts');$('#contacts').innerHTML=c.length?c.slice(0,40).map(x=>`<div class="item"><b>${x.payload?.first||''} ${x.payload?.last||''}</b><div>${x.payload?.street||''} ${x.payload?.civic||''}</div><small>${x.payload?.phone||''}</small></div>`).join(''):'<p class="status">Nessun contatto.</p>'}
async function refreshCloud(){if(!session)return;let s=await getSettings(),c=calc(s);$('#funnelSummary').innerHTML=`<div class="item"><b>Funnel sincronizzato dal PC</b><div>Vendite annue richieste: ${Math.ceil(c.sales)}</div><div>Incarichi: ${Math.ceil(c.mand)} · Appuntamenti: ${Math.ceil(c.appt)}</div><div>Notizie: ${Math.ceil(c.news)} · Conversazioni: ${Math.ceil(c.conv)}</div><div>Tentativi: ${Math.ceil(c.att)}</div></div>`}
function nav(n){$$('.screen').forEach(x=>x.classList.toggle('on',x.dataset.screen===n));$('#title').textContent=n==='today'?'OGGI':n.toUpperCase();if(n==='agenda')refreshAgenda();if(n==='crm')refreshCRM();if(n==='cloud')refreshCloud()}
async function render(){if(session){$('#acct').textContent=session.user.email;$('#cloudState').textContent='Connesso come '+session.user.email;$('#logout').style.display='block'}else{$('#acct').textContent='LOGIN';$('#cloudState').textContent='Non autenticato';$('#logout').style.display='none'}await refreshToday()}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$$('[data-inc]').forEach(b=>b.onclick=()=>increment(b.dataset.inc));$('#acct').onclick=()=>session?nav('cloud'):loginBox();$('#logout').onclick=async()=>{await sb.auth.signOut();session=null;render()};(async()=>{let {data}=await sb.auth.getSession();session=data.session;await render();sb.auth.onAuthStateChange((_e,s)=>{session=s;render()});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})})();