(function(){
"use strict";
const V7={tab:"dashboard",cursor:new Date(),mode:"week",folderHandles:{}};
const $=id=>document.getElementById(id), q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const h=s=>String(s==null?"":s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const pad=n=>String(n).padStart(2,"0"), key=d=>d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate());
const clone=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate()), add=(d,n)=>{const x=clone(d);x.setDate(x.getDate()+n);return x};
const startWeek=d=>{const x=clone(d);x.setDate(x.getDate()-((x.getDay()+6)%7));return x};
const dn=d=>["DOM","LUN","MAR","MER","GIO","VEN","SAB"][d.getDay()], mn=m=>["GENNAIO","FEBBRAIO","MARZO","APRILE","MAGGIO","GIUGNO","LUGLIO","AGOSTO","SETTEMBRE","OTTOBRE","NOVEMBRE","DICEMBRE"][m], sm=m=>["GEN","FEB","MAR","APR","MAG","GIU","LUG","AGO","SET","OTT","NOV","DIC"][m];
function activeClient(){try{return (clients||[]).find(c=>c.id===selectedClientId)||null}catch(_){return null}}
function scopedCal(){try{return (calendar||[]).filter(x=>!selectedClientId||x.client_id===selectedClientId)}catch(_){return[]}}
function plat(v){const p=String(v||"").toLowerCase();return {"facebook":"Facebook","instagram":"Instagram","linkedin-page":"LinkedIn","linkedin":"LinkedIn","tiktok":"TikTok","youtube":"YouTube"}[p]||v||"Social"}
function dt(x){return new Date(x.publication_at)} function title(x){return x.f1_content_items&&x.f1_content_items.title?x.f1_content_items.title:"Contenuto"}
function eventsFor(d){const k=key(d);return scopedCal().filter(x=>key(dt(x))===k).sort((a,b)=>dt(a)-dt(b))}
function chip(e,compact){const d=dt(e);return '<div class="f1v7-event"><b>'+pad(d.getHours())+":"+pad(d.getMinutes())+" · "+h(plat(e.platform))+'</b>'+(compact?'':('<span>'+h(title(e))+' · '+h(e.status||"")+'</span>'))+'</div>'}
function renderCal(host,mode,cursor){
 if(!host)return;
 if(mode==="day"){const ev=eventsFor(cursor);let out='<div class="f1v7-day"><div class="f1v7-day-head">'+dn(cursor)+" "+cursor.getDate()+" "+mn(cursor.getMonth())+" "+cursor.getFullYear()+'</div>';for(let hr=0;hr<=24;hr++){const slot=hr<24?ev.filter(x=>dt(x).getHours()===hr):[];out+='<div class="f1v7-hour-row"><div class="f1v7-hour-label">'+pad(hr)+':00</div><div class="f1v7-hour-cell">'+slot.map(x=>chip(x,false)).join("")+'</div></div>'}host.innerHTML=out+"</div>";return}
 if(mode==="week"){const s=startWeek(cursor),days=Array.from({length:7},(_,i)=>add(s,i));let out='<div class="f1v7-week-grid"><div class="f1v7-week-head">ORA</div>'+days.map(d=>'<div class="f1v7-week-head">'+dn(d)+" "+d.getDate()+'<br><span>'+sm(d.getMonth())+'</span></div>').join("");for(let hr=0;hr<=24;hr++){out+='<div class="f1v7-week-time">'+pad(hr)+':00</div>';days.forEach(d=>{const slot=hr<24?eventsFor(d).filter(x=>dt(x).getHours()===hr):[];out+='<div class="f1v7-week-cell">'+slot.map(x=>chip(x,false)).join("")+'</div>'})}host.innerHTML=out+"</div>";return}
 const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),gs=add(first,-((first.getDay()+6)%7)),days=Array.from({length:42},(_,i)=>add(gs,i));
 host.innerHTML='<div class="f1v7-month"><div class="f1v7-month-head"><div>LUN</div><div>MAR</div><div>MER</div><div>GIO</div><div>VEN</div><div>SAB</div><div>DOM</div></div><div class="f1v7-month-grid">'+days.map(d=>'<div class="f1v7-month-day '+(d.getMonth()!==m?"out ":"")+(key(d)===key(new Date())?"today":"")+'" data-date="'+key(d)+'"><b>'+d.getDate()+" "+sm(d.getMonth())+'</b>'+eventsFor(d).map(x=>chip(x,true)).join("")+'</div>').join("")+'</div></div>';
 qa(".f1v7-month-day",host).forEach(n=>n.onclick=()=>{const [yy,mm,dd]=n.dataset.date.split("-").map(Number);V7.cursor=new Date(yy,mm-1,dd);V7.mode="day";syncCal()});
}
function period(){if(V7.mode==="day")return dn(V7.cursor)+" "+V7.cursor.getDate()+" "+mn(V7.cursor.getMonth())+" "+V7.cursor.getFullYear();if(V7.mode==="month")return mn(V7.cursor.getMonth())+" "+V7.cursor.getFullYear();const s=startWeek(V7.cursor),e=add(s,6);return s.getDate()+" "+sm(s.getMonth())+" — "+e.getDate()+" "+sm(e.getMonth())+" "+e.getFullYear()}
function syncCal(){const host=$("weekCalendar");if(host){host.className="f1v7-calendar-shell";renderCal(host,V7.mode,V7.cursor)}const l=$("weekLabel");if(l)l.textContent=period();const ph=$("f1v7PubCalHost");if(ph)renderCal(ph,V7.mode,V7.cursor);const pl=$("f1v7PubPeriod");if(pl)pl.textContent=period()}
window.f1CalendarMode=mode=>{V7.mode=mode;syncCal()};window.f1CalendarToday=()=>{V7.cursor=new Date();syncCal()};window.f1CalendarMove=dir=>{V7.cursor=V7.mode==="month"?new Date(V7.cursor.getFullYear(),V7.cursor.getMonth()+dir,1):add(V7.cursor,dir*(V7.mode==="week"?7:1));syncCal()};
function ensurePub(){const sec=$("tab-publications");if(!sec||$("f1v7PublicationCalendar"))return;const p=sec.querySelector(".panel");if(!p)return;const box=document.createElement("div");box.id="f1v7PublicationCalendar";box.innerHTML='<div class="section-title"><div><h2>Calendario editoriale</h2><div class="muted" id="f1v7PubClient"></div></div></div><div class="week-toolbar"><div class="row"><button class="btn small ghost" onclick="window.f1CalendarMove(-1)">←</button><button class="btn small ghost" onclick="window.f1CalendarToday()">OGGI</button><button class="btn small ghost" onclick="window.f1CalendarMove(1)">→</button></div><b id="f1v7PubPeriod"></b><div class="row"><button class="btn small ghost" onclick="window.f1CalendarMode(\'month\')">MESE</button><button class="btn small primary" onclick="window.f1CalendarMode(\'week\')">SETTIMANA</button><button class="btn small ghost" onclick="window.f1CalendarMode(\'day\')">GIORNO</button></div></div><div id="f1v7PubCalHost" class="f1v7-calendar-shell"></div><div class="section-title" style="margin-top:14px"><h3 style="margin:0">Pubblicazioni sui canali social</h3></div>';p.prepend(box)}
function renderDash(){if(!$("metrics")||!$("clientCards"))return;const now=Date.now(),future=(calendar||[]).filter(x=>new Date(x.publication_at).getTime()>=now).length,blocked=(calendar||[]).filter(x=>/ERRORE|AUTH|CREDENZIALI|CANALE_DA_COLLEGARE|RIAUTORIZZARE/.test(String(x.status||""))).length,active=(clients||[]).filter(c=>String(c.status||"ATTIVO")==="ATTIVO").length;$("metrics").className="metrics f1v7-metrics";$("metrics").innerHTML=[["CLIENTI ATTIVI",active],["CONTENUTI",(items||[]).length],["PROGRAMMATI",future],["PROBLEMI",blocked]].map(x=>'<div class="metric"><b>'+x[1]+'</b><span>'+x[0]+'</span></div>').join("");$("clientCards").className="";$("clientCards").innerHTML=(clients||[]).filter(c=>String(c.status||"ATTIVO")!=="ARCHIVIATO").map(c=>{const ci=(items||[]).filter(x=>x.client_id===c.id),cal=(calendar||[]).filter(x=>x.client_id===c.id),soc=(socialChannels||[]).filter(x=>x.client_id===c.id),con=soc.filter(x=>x.enabled&&x.verified).length,pro=cal.filter(x=>/ERRORE|AUTH|CREDENZIALI|CANALE_DA_COLLEGARE|RIAUTORIZZARE/.test(String(x.status||""))).length,desc=[c.category,c.territory].filter(Boolean).join(" · ")||"Cliente F1 Social";return '<div class="f1v7-dashboard-row '+(selectedClientId===c.id?"active":"")+'"><div><small>CLIENTE</small><h3>'+h(c.name)+'</h3><div class="meta">'+h(desc)+'</div></div><div class="f1v7-service-strip"><span class="badge '+(con?"green":"amber")+'">SOCIAL '+con+'/'+soc.length+'</span><span class="badge">EMAIL</span><span class="badge">'+(c.website?"SITO":"SITO —")+'</span><span class="badge">ADV</span></div><div class="f1v7-kpis"><span><b>'+ci.length+'</b>CONTENUTI</span><span><b>'+con+'</b>CANALI</span><span><b>'+cal.filter(x=>new Date(x.publication_at).getTime()>=now).length+'</b>PROGRAMMATI</span><span><b>'+pro+'</b>PROBLEMI</span></div><button class="btn small primary" onclick="window.f1V7OpenClient(\''+c.id+'\')">APRI</button></div>'}).join("")}
window.f1V7OpenClient=id=>{window.f1SetClientScope&&window.f1SetClientScope(id);setTimeout(()=>setTab("archive"),0)};
function ensureDash(){const nav=q('[data-tab="clients"]');if(nav)nav.classList.add("f1v7-hidden");const latest=$("latestGrid");if(latest&&latest.closest(".panel"))latest.closest(".panel").classList.add("f1v7-hidden");const card=$("clientCards");if(card){const st=card.closest(".panel")&&card.closest(".panel").querySelector(".section-title");if(st)st.classList.add("f1v7-hidden")}const old=$("openClientBtn"),top=$("openUploadBtn")&&$("openUploadBtn").parentElement;if(old&&top&&!$("f1v7NewClientBtn")){old.id="f1v7NewClientBtn";old.textContent="+ NUOVO CLIENTE";top.insertBefore(old,$("openUploadBtn"))}}
function idb(){return new Promise((res,rej)=>{const r=indexedDB.open("f1-social-local-folders",1);r.onupgradeneeded=()=>r.result.createObjectStore("handles");r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function saveHandle(cid,handle){const db=await idb();await new Promise((res,rej)=>{const tx=db.transaction("handles","readwrite");tx.objectStore("handles").put(handle,cid);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getHandle(cid){const db=await idb();return new Promise((res,rej)=>{const r=db.transaction("handles").objectStore("handles").get(cid);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function chooseFolder(){const c=activeClient();if(!c)throw new Error("Seleziona un cliente.");if(!window.showDirectoryPicker)throw new Error("Browser non compatibile con cartelle persistenti.");const handle=await showDirectoryPicker({mode:"readwrite"});await saveHandle(c.id,handle);V7.folderHandles[c.id]=handle;const s=$("f1v7FolderStatus");if(s)s.textContent="Cartella collegata: "+handle.name}
async function archiveFiles(){const c=activeClient();if(!c)throw new Error("Seleziona un cliente.");let handle=V7.folderHandles[c.id]||await getHandle(c.id).catch(()=>null);if(!handle){await chooseFolder();handle=V7.folderHandles[c.id]||await getHandle(c.id)}if(!window.showOpenFilePicker)throw new Error("Usa Chrome/Edge per il salvataggio locale.");const files=await showOpenFilePicker({multiple:true});for(const fh of files){const file=await fh.getFile(),dest=await handle.getFileHandle(file.name,{create:true}),w=await dest.createWritable();await w.write(file);await w.close()}const s=$("f1v7FolderStatus");if(s)s.textContent=files.length+" file salvati per "+c.name}
window.f1V7ChooseFolder=()=>chooseFolder().catch(e=>alert(e.message||e));window.f1V7ArchiveFiles=()=>archiveFiles().catch(e=>alert(e.message||e));window.f1V7Whatsapp=()=>setTab("whatsapp");
function ensureArchive(){const sec=$("tab-archive");if(!sec)return;const cf=$("clientFilter");if(cf)cf.classList.add("f1v7-hidden");if(!$("f1v7ContentHeader")){const head=document.createElement("div");head.id="f1v7ContentHeader";head.className="panel";head.innerHTML='<div class="section-title"><div><h2 id="f1v7ContentTitle">Contenuti</h2><div class="muted">Archivio esclusivo del cliente selezionato</div></div></div><div class="f1v7-content-actions"><button class="f1v7-action" onclick="window.f1V7ArchiveFiles()">DA FILE<span>Salva nella cartella locale del cliente</span></button><button class="f1v7-action" onclick="window.f1V7Whatsapp()">DA WHATSAPP<span>Apri i contenuti ricevuti</span></button><button class="f1v7-action" onclick="document.getElementById(\'archiveGrid\').scrollIntoView({behavior:\'smooth\'})">GIÀ INSERITI<span>Archivio del cliente</span></button><button class="f1v7-action" onclick="window.f1V7ChooseFolder()">APRI CARTELLA CLIENTE<span>Collega la cartella sul PC</span></button></div><div id="f1v7FolderStatus" class="meta" style="margin-top:8px">Nessuna cartella locale collegata.</div>';sec.prepend(head)}}
function enhanceConnections(){const sec=$("tab-connections");if(!sec)return;qa(".lineitem",sec).forEach(row=>{const badge=q(".badge",row);if(!badge||badge.textContent.trim()==="COLLEGATO")return;qa("button",row).forEach(b=>{if(/COLLEGA|RIAUTORIZZA|SELEZIONA|CONFIGURA/.test(b.textContent))b.textContent="RISOLVI"})})}
function syncView(tab){V7.tab=tab||V7.tab;const dash=V7.tab==="dashboard",sel=$("globalClientSelect");if(sel){sel.disabled=dash;if(dash)sel.value=""}const ctx=$("clientContext");if(ctx)ctx.classList.toggle("f1v7-hidden",dash||V7.tab==="analytics");const rail=$("contentRailToggleBtn");if(rail)rail.classList.toggle("f1v7-hidden",dash);const prob=$("problemQuickBtn");if(prob)prob.classList.toggle("f1v7-hidden",dash);const nc=$("f1v7NewClientBtn");if(nc)nc.classList.toggle("f1v7-hidden",!dash);if(dash)renderDash();if(V7.tab==="archive"){const t=$("f1v7ContentTitle");if(t)t.textContent="Contenuti · "+(activeClient()?.name||"Cliente")}if(V7.tab==="calendar")syncCal();if(V7.tab==="publications"){ensurePub();const p=$("f1v7PubClient");if(p)p.textContent="Programmazioni future · "+(activeClient()?.name||"Tutti i clienti");syncCal()}if(V7.tab==="connections")setTimeout(enhanceConnections,0);if(V7.tab==="email"&&window.f1V7RenderEmailCompact)setTimeout(window.f1V7RenderEmailCompact,300)}
function boot(){ensureDash();ensureArchive();ensurePub();if(typeof setTab==="function"){const old=setTab;setTab=function(tab,opt){old(tab,opt);syncView(tab)};window.setTab=setTab}if(typeof renderAll==="function"){const oldR=renderAll;renderAll=async function(){const out=await oldR();ensureDash();ensureArchive();renderDash();syncView(V7.tab);return out}}qa("[data-tab]").forEach(b=>b.addEventListener("click",()=>setTimeout(()=>syncView(b.dataset.tab),0)));V7.cursor=new Date();syncView("dashboard")}
window.F1V7=V7;if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(boot,0));else setTimeout(boot,0);
})();