import fs from 'node:fs';
import path from 'node:path';
import {Resvg} from '@resvg/resvg-js';
import sharp from 'sharp';

const DESIGN_VERSION='F1_REFERENCE_FEED_V5';
const W=1080,H=1350;
function arg(name){const i=process.argv.indexOf(name);if(i<0||!process.argv[i+1])throw new Error(`Missing ${name}`);return process.argv[i+1];}
function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');}
function clean(v=''){return String(v).replace(/\s+/g,' ').trim();}
function wrap(text,max=12,maxLines=3){const words=clean(String(text||'').replaceAll('|',' ')).split(' ').filter(Boolean),out=[];let line='';for(const word of words){const n=line?`${line} ${word}`:word;if(line&&n.length>max){out.push(line);line=word;}else line=n;}if(line)out.push(line);return out.slice(0,maxLines);}
function slidePayload(spec,index){const slides=Array.isArray(spec.content?.slides)?spec.content.slides:[];const row=slides[index];if(typeof row==='string')return{title:row};if(row&&typeof row==='object')return row;return spec.content||{};}
function logoMark(x,y,s,dark,green){return `<g transform="translate(${x} ${y}) scale(${s})"><path d="M4 30 L54 2 L99 26" fill="none" stroke="${green}" stroke-width="5"/><path d="M23 29 L23 9" stroke="${green}" stroke-width="4"/><path d="M27 40 L88 40 L80 55 L52 55 L46 67 L74 67 L66 82 L30 82 L20 94 L4 94 L30 40 Z" fill="${dark}"/><path d="M92 37 L116 37 L101 94 L80 94 L88 65 L66 65 L75 49 Z" fill="${green}"/></g>`;}
function wordmark(x,y,dark,green){return `<g>${logoMark(x,y,1.02,dark,green)}<text x="${x+137}" y="${y+61}" fill="${dark}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="34" font-weight="900">IMMOBILIARE</text><text x="${x+140}" y="${y+92}" fill="${dark}" font-family="DejaVu Sans,Arial,sans-serif" font-size="14" font-weight="700" letter-spacing="5">CASA E IMPRESE</text><line x1="${x+138}" y1="${y+108}" x2="${x+374}" y2="${y+108}" stroke="${green}" stroke-width="3"/><text x="${x+140}" y="${y+132}" fill="${dark}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="12" font-weight="800" letter-spacing="2">LA TUA CASA, IL NOSTRO OBIETTIVO</text></g>`;}
function titleSize(lines){const longest=Math.max(...lines.map(x=>x.length),1);return longest>=12?45:longest>=10?50:56;}
function titleMarkup(lines,x,y,dark,green){const size=titleSize(lines);return `<text x="${x}" y="${y}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="${size}" font-weight="900">${lines.map((line,i)=>`<tspan x="${x}" dy="${i?size*.98:0}" fill="${i===lines.length-1&&lines.length>1?green:dark}">${esc(line.toUpperCase())}</tspan>`).join('')}</text>`;}
function iconCircle(cx,cy,green){return `<circle cx="${cx}" cy="${cy}" r="21" fill="${green}"/><text x="${cx}" y="${cy+7}" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="22" font-weight="900">✓</text>`;}
function diagonal(dark,green){return `<path d="M500 0 H540 L420 196 H380 Z" fill="${dark}"/><path d="M546 0 H570 L450 196 H426 Z" fill="${green}"/><path d="M574 0 H583 L463 196 H454 Z" fill="#BEE5A7"/>`;}
function header(brand,dark,green){const script=brand.script_tagline||'Affidati a chi conosce il territorio';return `<g><rect width="1080" height="196" fill="#fff"/>${wordmark(34,23,dark,green)}${diagonal(dark,green)}<text x="1030" y="62" text-anchor="end" fill="${dark}" font-family="DejaVu Serif,Georgia,serif" font-size="24" font-style="italic" font-weight="600">${esc(script)}</text><path d="M760 91 C850 70 934 70 1025 84" fill="none" stroke="${green}" stroke-width="4"/></g>`;}
function proofRows(proofs,x,y,green,dark){return (proofs||[]).slice(0,3).map((p,i)=>`${iconCircle(x,y+i*68,green)}<text x="${x+40}" y="${y+7+i*68}" fill="${dark}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="18" font-weight="800">${esc(clean(p).toUpperCase().slice(0,26))}</text>`).join('');}
function feedBody(spec,content,image,dark,green){const family=String(spec.metadata?.family||'institutional');const title=wrap(content.title||spec.content?.cover_title||spec.content?.title,12,3);const subtitle=wrap(content.subtitle||spec.content?.subtitle||'',31,2);const proofs=Array.isArray(spec.content?.proofs)?spec.content.proofs:[];const imageHref=image?esc(image):'';const cta=clean(spec.content?.short_cta||'SCRIVI VALUTAZIONE');
 const hero=`<clipPath id="hero"><path d="M515 196 H1080 V1080 H410 Z"/></clipPath>${imageHref?`<image href="${imageHref}" x="405" y="196" width="675" height="884" preserveAspectRatio="xMidYMid slice" clip-path="url(#hero)"/>`:`<path d="M515 196 H1080 V1080 H410 Z" fill="#E9ECE7"/>`}<path d="M486 196 H520 L418 1080 H384 Z" fill="${dark}"/><path d="M526 196 H545 L443 1080 H424 Z" fill="${green}"/>`;
 const titleY=family==='recruiting'?355:370;const titleBlock=titleMarkup(title,38,titleY,dark,green);const lineY=titleY+190;const sub=subtitle.length?`<line x1="38" y1="${lineY}" x2="220" y2="${lineY}" stroke="${green}" stroke-width="4"/>${subtitle.map((s,i)=>`<text x="38" y="${lineY+40+i*30}" fill="#404740" font-family="DejaVu Sans,Arial,sans-serif" font-size="19">${esc(s)}</text>`).join('')}`:'';const list=proofRows(proofs,60,family==='recruiting'?700:715,green,dark);const boxW=390;const ctaBox=`<rect x="38" y="955" width="${boxW}" height="72" rx="10" fill="${green}"/><text x="${38+boxW/2}" y="1002" text-anchor="middle" fill="#fff" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="27" font-weight="900">${esc(cta.toUpperCase().slice(0,24))}</text>`;const price=clean(spec.content?.price||'');const priceBadge=price?`<g transform="translate(790 220) rotate(-4)"><rect x="0" y="0" width="250" height="88" rx="10" fill="${green}" stroke="#fff" stroke-width="4"/><text x="125" y="58" text-anchor="middle" fill="#fff" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="39" font-weight="900">${esc(price)}</text></g>`:'';return `<g><rect x="0" y="196" width="1080" height="884" fill="#fff"/>${hero}${titleBlock}${sub}${list}${ctaBox}${priceBadge}<path d="M0 1042 H390 L355 1080 H0 Z" fill="${green}"/></g>`;}
function lowerPanel(spec,brand,dark,green){const proofs=Array.isArray(spec.content?.proofs)?spec.content.proofs:[];const p=[...proofs,'METODO F1','TERRITORIO'].slice(0,3);const phone1=brand.phone_primary||'+39 371 370 8294',phone2=brand.phone_secondary||'+39 371 424 6300',site=brand.site||'www.f1immobiliare.com';return `<g><rect x="0" y="1080" width="1080" height="270" fill="#fff"/><rect x="0" y="1080" width="1080" height="6" fill="${green}"/>${p.map((v,i)=>{const x=25+i*353;return `<rect x="${x}" y="1100" width="338" height="72" rx="9" fill="#fff" stroke="#D8DDD5"/><circle cx="${x+37}" cy="1136" r="22" fill="#fff" stroke="${green}" stroke-width="3"/><text x="${x+37}" y="1144" text-anchor="middle" fill="${green}" font-size="21" font-weight="900">✓</text><text x="${x+70}" y="1142" fill="${dark}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="15" font-weight="900">${esc(clean(v).toUpperCase().slice(0,23))}</text>`}).join('')}<circle cx="59" cy="1219" r="38" fill="${green}"/><text x="59" y="1232" text-anchor="middle" fill="#fff" font-size="34" font-weight="900">☎</text><text x="110" y="1206" fill="${dark}" font-family="DejaVu Sans,Arial,sans-serif" font-size="14">Per info e visite:</text><text x="110" y="1245" fill="${green}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="35" font-weight="900">${esc(phone1.replace('+39 ',''))}</text><line x1="470" y1="1193" x2="470" y2="1252" stroke="#B9BDB8"/><text x="500" y="1206" fill="#555" font-family="DejaVu Sans,Arial,sans-serif" font-size="13">Ufficio secondario:</text><text x="500" y="1244" fill="${green}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="29" font-weight="900">${esc(phone2.replace('+39 ',''))}</text><rect x="0" y="1270" width="1080" height="80" fill="${dark}"/>${logoMark(438,1280,.52,'#fff',green)}<text x="500" y="1317" fill="#fff" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="18" font-weight="900">IMMOBILIARE</text><text x="39" y="1314" fill="#fff" font-family="DejaVu Sans,Arial,sans-serif" font-size="15">Via Roma, 8 · Sant'Antonino di Susa (TO)</text><text x="1027" y="1306" text-anchor="end" fill="#fff" font-family="DejaVu Sans,Arial,sans-serif" font-size="15">${esc(site)}</text><text x="1027" y="1330" text-anchor="end" fill="${green}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="14" font-weight="900">CASE · PERSONE · TERRITORIO · FUTURO</text></g>`;}
function buildSvg(spec,index=0){const brand=spec.brand||{},dark=brand.secondary||'#0A0D0A',green=brand.primary||'#4E9E15',content=slidePayload(spec,index),images=spec.assets?.images||[],image=content.image||images[index]||images[0]||'';return `<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="${W}" height="${H}" fill="#fff"/>${header(brand,dark,green)}${feedBody(spec,content,image,dark,green)}${lowerPanel(spec,brand,dark,green)}</svg>`;}
async function renderOne(spec,output,index){const png=new Resvg(buildSvg(spec,index),{fitTo:{mode:'width',value:W}}).render().asPng();await sharp(png).jpeg({quality:Number(spec.output?.quality||95),mozjpeg:true}).toFile(output);}
async function main(){const specPath=arg('--spec'),outputArg=arg('--output'),spec=JSON.parse(fs.readFileSync(specPath,'utf8'));if(String(spec.metadata?.golden_master_version||'')!==DESIGN_VERSION)throw new Error(`Golden Master mismatch: expected ${DESIGN_VERSION}`);if(spec.metadata?.feed_first!==true||spec.metadata?.locked_template!==true)throw new Error('Reference feed requires feed_first=true and locked_template=true');const slides=Array.isArray(spec.content?.slides)&&spec.content.slides.length?spec.content.slides:[spec.content||{}],outputs=[],parsed=path.parse(outputArg);if(spec.type==='carousel'){for(let i=0;i<slides.length;i++){const file=path.resolve(parsed.dir,`${parsed.name}-${String(i+1).padStart(2,'0')}${parsed.ext||'.jpg'}`);fs.mkdirSync(path.dirname(file),{recursive:true});await renderOne(spec,file,i);outputs.push(file);}}else{const file=path.resolve(outputArg);fs.mkdirSync(path.dirname(file),{recursive:true});await renderOne(spec,file,0);outputs.push(file);}console.log(JSON.stringify({status:'STATIC_RENDER_OK',engine:'svg-resvg-sharp',design_version:DESIGN_VERSION,outputs}));}
main().catch(error=>{console.error(error?.stack||String(error));process.exit(1);});