import fs from 'node:fs';
import path from 'node:path';
import {Resvg} from '@resvg/resvg-js';
import sharp from 'sharp';

const DESIGN_VERSION='F1_REFERENCE_FEED_V5';
const W=1080,H=1350;
function arg(name){const i=process.argv.indexOf(name);if(i<0||!process.argv[i+1])throw new Error(`Missing ${name}`);return process.argv[i+1];}
function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');}
function clean(v=''){return String(v).replace(/\s+/g,' ').trim();}
function wrap(text,max=13,maxLines=4){const words=clean(String(text||'').replaceAll('|',' ')).split(' ').filter(Boolean),out=[];let line='';for(const word of words){const n=line?`${line} ${word}`:word;if(line&&n.length>max){out.push(line);line=word;}else line=n;}if(line)out.push(line);return out.slice(0,maxLines);}
function slidePayload(spec,index){const slides=Array.isArray(spec.content?.slides)?spec.content.slides:[];const row=slides[index];if(typeof row==='string')return{title:row};if(row&&typeof row==='object')return row;return spec.content||{};}
function logoMark(x,y,s,dark,green){return `<g transform="translate(${x} ${y}) scale(${s})"><path d="M4 30 L54 2 L99 26" fill="none" stroke="${green}" stroke-width="5" stroke-linecap="round"/><path d="M23 29 L23 9" stroke="${green}" stroke-width="4"/><path d="M27 40 L88 40 L80 55 L52 55 L46 67 L74 67 L66 82 L30 82 L20 94 L4 94 L30 40 Z" fill="${dark}"/><path d="M92 37 L116 37 L101 94 L80 94 L88 65 L66 65 L75 49 Z" fill="${green}"/></g>`;}
function wordmark(x,y,dark,green){return `<g>${logoMark(x,y,1.18,dark,green)}<text x="${x+160}" y="${y+69}" fill="${dark}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="39" font-weight="900">IMMOBILIARE</text><text x="${x+162}" y="${y+106}" fill="${dark}" font-family="DejaVu Sans,Arial,sans-serif" font-size="16" font-weight="700" letter-spacing="6">CASA E IMPRESE</text><line x1="${x+160}" y1="${y+122}" x2="${x+431}" y2="${y+122}" stroke="${green}" stroke-width="3"/><text x="${x+162}" y="${y+147}" fill="${dark}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="13" font-weight="800" letter-spacing="2">LA TUA CASA, IL NOSTRO OBIETTIVO</text></g>`;}
function titleSize(lines){const longest=Math.max(...lines.map(x=>x.length),1);return longest>=15?49:longest>=12?55:longest>=9?61:68;}
function titleMarkup(lines,x,y,dark,green){const size=titleSize(lines);return `<text x="${x}" y="${y}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="${size}" font-weight="900">${lines.map((line,i)=>`<tspan x="${x}" dy="${i?size*.96:0}" fill="${i===lines.length-1&&lines.length>1?green:dark}">${esc(line.toUpperCase())}</tspan>`).join('')}</text>`;}
function diagonal(dark,green){return `<path d="M488 0 H532 L390 221 H347 Z" fill="${dark}"/><path d="M539 0 H566 L423 221 H397 Z" fill="${green}"/><path d="M572 0 H582 L440 221 H430 Z" fill="#D9EBCF"/>`;}
function header(brand,dark,green){const script=brand.script_tagline||'Affidati a chi conosce il territorio';return `<g><rect width="1080" height="221" fill="#fff"/>${wordmark(27,18,dark,green)}${diagonal(dark,green)}<text x="1032" y="55" text-anchor="end" fill="${dark}" font-family="URW Chancery L,DejaVu Serif,Georgia,serif" font-size="25" font-style="italic" font-weight="600">${esc(script)}</text><path d="M765 86 C850 70 938 72 1028 82" fill="none" stroke="${green}" stroke-width="4" stroke-linecap="round"/></g>`;}
function factIcon(cx,cy,green,symbol='✓'){return `<circle cx="${cx}" cy="${cy}" r="23" fill="url(#g)"/><text x="${cx}" y="${cy+8}" text-anchor="middle" fill="#fff" font-family="DejaVu Sans,Arial,sans-serif" font-size="22" font-weight="900">${esc(symbol)}</text>`;}
function factRows(items,x,y,green,dark,max=6){return items.slice(0,max).map((p,i)=>{const yy=y+i*67;return `${factIcon(x,yy,green,'✓')}<text x="${x+43}" y="${yy+7}" fill="${dark}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="18" font-weight="800">${esc(clean(p).slice(0,29))}</text><line x1="${x+43}" y1="${yy+23}" x2="${x+280}" y2="${yy+23}" stroke="#D5D8D4" stroke-width="1" stroke-dasharray="3 4"/>`;}).join('');}
function heroImage(image){const href=image?esc(image):'';return href?`<image href="${href}" x="388" y="221" width="692" height="644" preserveAspectRatio="xMidYMid slice" clip-path="url(#hero)"/>`:`<path d="M520 221 H1080 V865 H386 Z" fill="#E9ECE7"/>`;}
function propertyBody(spec,content,image,dark,green){const title=wrap(content.title||spec.content?.cover_title||spec.content?.title,12,4),loc=clean(content.location||spec.content?.location||''),sub=clean(content.subtitle||spec.content?.subtitle||''),price=clean(content.price||spec.content?.price||''),features=(Array.isArray(content.features)?content.features:spec.content?.features)||[],proofs=(Array.isArray(spec.content?.proofs)?spec.content.proofs:[]);const facts=features.length?features:[...proofs,'AMBIENTI LUMINOSI','ZONA COMODA'];return `<g><rect x="0" y="221" width="1080" height="859" fill="#fff"/>${heroImage(image)}<path d="M505 221 H548 L410 865 H368 Z" fill="${dark}"/><path d="M552 221 H579 L440 865 H414 Z" fill="${green}"/>${titleMarkup(title,31,360,dark,green)}${loc?`<text x="32" y="${360+title.length*65+28}" fill="${green}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="29" font-weight="800">${esc(loc)}</text><line x1="32" y1="${360+title.length*65+43}" x2="315" y2="${360+title.length*65+43}" stroke="${green}" stroke-width="3"/>`:''}${sub?`<text x="32" y="${loc?635:600}" fill="#333" font-family="DejaVu Sans,Arial,sans-serif" font-size="19">${esc(sub.slice(0,43))}</text>`:''}${price?`<g transform="translate(46 710)"><rect width="285" height="82" rx="9" fill="url(#g)"/><text x="142" y="57" text-anchor="middle" fill="#fff" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="44" font-weight="900">${esc(price)}</text></g>`:''}${factRows(facts,59,price?836:720,green,dark,price?3:5)}<g transform="translate(770 258) rotate(-4)"><rect width="270" height="94" rx="10" fill="${dark}" stroke="#fff" stroke-width="4"/><text x="135" y="32" text-anchor="middle" fill="#fff" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="22" font-weight="900">IN VENDITA</text><text x="135" y="70" text-anchor="middle" fill="${green}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="36" font-weight="900">${esc(price||'SCOPRI DI PIÙ')}</text></g><path d="M0 1035 H360 L332 1080 H0 Z" fill="url(#g)"/></g>`;}
function recruitingBody(spec,content,image,dark,green){const title=wrap(content.title||spec.content?.cover_title||spec.content?.title,12,4),sub=wrap(content.subtitle||spec.content?.subtitle||'',30,3),proofs=Array.isArray(spec.content?.proofs)?spec.content.proofs:[];return `<g><rect x="0" y="221" width="1080" height="859" fill="#fff"/>${heroImage(image)}<path d="M505 221 H548 L410 865 H368 Z" fill="${dark}"/><path d="M552 221 H579 L440 865 H414 Z" fill="${green}"/>${titleMarkup(title,31,372,dark,green)}${sub.map((s,i)=>`<text x="32" y="${640+i*30}" fill="#242724" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="21" font-weight="700">${esc(s)}</text>`).join('')}${factRows(proofs.length?proofs:['FORMAZIONE INTERNA','PERCORSO DI CRESCITA','SUPPORTO COSTANTE'],59,765,green,dark,4)}<rect x="32" y="978" width="302" height="72" rx="9" fill="url(#g)"/><text x="183" y="1025" text-anchor="middle" fill="#fff" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="27" font-weight="900">CANDIDATI ORA</text><path d="M0 1035 H360 L332 1080 H0 Z" fill="url(#g)"/></g>`;}
function institutionalBody(spec,content,image,dark,green){const title=wrap(content.title||spec.content?.cover_title||spec.content?.title,12,4),sub=wrap(content.subtitle||spec.content?.subtitle||'',31,3),proofs=Array.isArray(spec.content?.proofs)?spec.content.proofs:[];return `<g><rect x="0" y="221" width="1080" height="859" fill="#fff"/>${heroImage(image)}<path d="M505 221 H548 L410 865 H368 Z" fill="${dark}"/><path d="M552 221 H579 L440 865 H414 Z" fill="${green}"/>${titleMarkup(title,31,376,dark,green)}${sub.map((s,i)=>`<text x="32" y="${640+i*30}" fill="#333" font-family="DejaVu Sans,Arial,sans-serif" font-size="19">${esc(s)}</text>`).join('')}${factRows(proofs.length?proofs:['METODO F1','TERRITORIO','STRATEGIA'],59,760,green,dark,4)}<rect x="32" y="978" width="322" height="72" rx="9" fill="url(#g)"/><text x="193" y="1025" text-anchor="middle" fill="#fff" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="26" font-weight="900">SCRIVI VALUTAZIONE</text><path d="M0 1035 H360 L332 1080 H0 Z" fill="url(#g)"/></g>`;}
function benefitCard(x,y,w,title,body,green,dark){return `<rect x="${x}" y="${y}" width="${w}" height="76" rx="10" fill="#fff" stroke="#C8CEC4"/><circle cx="${x+39}" cy="${y+38}" r="25" fill="#fff" stroke="${green}" stroke-width="3"/><circle cx="${x+39}" cy="${y+38}" r="8" fill="${green}"/><text x="${x+77}" y="${y+30}" fill="${dark}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="15" font-weight="900">${esc(title)}</text><text x="${x+77}" y="${y+52}" fill="#444" font-family="DejaVu Sans,Arial,sans-serif" font-size="12">${esc(body)}</text>`;}
function lowerPanel(spec,brand,dark,green){const phone1=brand.phone_primary||'+39 371 370 8294',phone2=brand.phone_secondary||'+39 371 424 6300',site=brand.site||'www.f1immobiliare.com';return `<g><rect x="0" y="1080" width="1080" height="270" fill="#fff"/>${benefitCard(22,1094,330,'AMBIENTI LUMINOSI','La luce protagonista in ogni spazio.',green,dark)}${benefitCard(375,1094,330,'ZONA COMODA E SERVITA','Tutti i servizi a pochi passi.',green,dark)}${benefitCard(728,1094,330,'IDEALE PER FAMIGLIE','Spazi ampi e ben distribuiti.',green,dark)}<rect x="22" y="1183" width="735" height="82" rx="12" fill="#fff" stroke="#BFC5BC"/><circle cx="74" cy="1224" r="38" fill="url(#g)"/><text x="74" y="1236" text-anchor="middle" fill="#fff" font-size="31" font-weight="900">☎</text><text x="126" y="1208" fill="${dark}" font-family="DejaVu Sans,Arial,sans-serif" font-size="14">Per info e visite:</text><text x="126" y="1247" fill="${green}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="36" font-weight="900">${esc(phone1.replace('+39 ',''))}</text><line x1="477" y1="1197" x2="477" y2="1252" stroke="#B9BDB8"/><text x="503" y="1208" fill="#555" font-family="DejaVu Sans,Arial,sans-serif" font-size="13">Ufficio secondario:</text><text x="503" y="1245" fill="${green}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="28" font-weight="900">${esc(phone2.replace('+39 ',''))}</text><rect x="780" y="1183" width="278" height="82" rx="10" fill="#fff" stroke="${green}"/><rect x="801" y="1198" width="50" height="50" fill="#111"/><rect x="808" y="1205" width="14" height="14" fill="#fff"/><rect x="832" y="1205" width="12" height="12" fill="#fff"/><rect x="808" y="1229" width="12" height="12" fill="#fff"/><text x="875" y="1215" fill="${dark}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="16" font-weight="900">VISITA</text><text x="875" y="1235" fill="${dark}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="16" font-weight="900">IL NOSTRO</text><text x="875" y="1255" fill="${dark}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="16" font-weight="900">SITO WEB</text><rect x="0" y="1275" width="1080" height="75" fill="${dark}"/><text x="31" y="1318" fill="#fff" font-family="DejaVu Sans,Arial,sans-serif" font-size="14">● Via Roma, 8 · Sant'Antonino di Susa (TO)</text>${logoMark(431,1284,.48,'#fff',green)}<text x="490" y="1318" fill="#fff" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="18" font-weight="900">IMMOBILIARE</text><text x="1028" y="1307" text-anchor="end" fill="#fff" font-family="DejaVu Sans,Arial,sans-serif" font-size="14">${esc(site)}</text><text x="1028" y="1330" text-anchor="end" fill="${green}" font-family="DejaVu Sans Condensed,Arial,sans-serif" font-size="13" font-weight="900">CASE · PERSONE · TERRITORIO · FUTURO</text></g>`;}
function buildSvg(spec,index=0){const brand=spec.brand||{},dark=brand.secondary||'#0A0D0A',green=brand.primary||'#4E9E15',content={...spec.content,...slidePayload(spec,index)},images=spec.assets?.images||[],image=content.image||images[index]||images[0]||'',family=String(spec.metadata?.family||'institutional');const body=family==='property'?propertyBody(spec,content,image,dark,green):family==='recruiting'?recruitingBody(spec,content,image,dark,green):institutionalBody(spec,content,image,dark,green);return `<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#63C20A"/><stop offset="1" stop-color="#2D7F08"/></linearGradient><clipPath id="hero"><path d="M520 221 H1080 V865 H386 Z"/></clipPath></defs><rect width="${W}" height="${H}" fill="#fff"/>${header(brand,dark,green)}${body}${lowerPanel(spec,brand,dark,green)}</svg>`;}
async function renderOne(spec,output,index){const png=new Resvg(buildSvg(spec,index),{fitTo:{mode:'width',value:W}}).render().asPng();await sharp(png).jpeg({quality:Number(spec.output?.quality||95),mozjpeg:true}).toFile(output);}
async function main(){const specPath=arg('--spec'),outputArg=arg('--output'),spec=JSON.parse(fs.readFileSync(specPath,'utf8'));if(String(spec.metadata?.golden_master_version||'')!==DESIGN_VERSION)throw new Error(`Golden Master mismatch: expected ${DESIGN_VERSION}`);if(spec.metadata?.feed_first!==true||spec.metadata?.locked_template!==true)throw new Error('Reference feed requires feed_first=true and locked_template=true');const slides=Array.isArray(spec.content?.slides)&&spec.content.slides.length?spec.content.slides:[spec.content||{}],outputs=[],parsed=path.parse(outputArg);if(spec.type==='carousel'){for(let i=0;i<slides.length;i++){const file=path.resolve(parsed.dir,`${parsed.name}-${String(i+1).padStart(2,'0')}${parsed.ext||'.jpg'}`);fs.mkdirSync(path.dirname(file),{recursive:true});await renderOne(spec,file,i);outputs.push(file);}}else{const file=path.resolve(outputArg);fs.mkdirSync(path.dirname(file),{recursive:true});await renderOne(spec,file,0);outputs.push(file);}console.log(JSON.stringify({status:'STATIC_RENDER_OK',engine:'svg-resvg-sharp',design_version:DESIGN_VERSION,outputs}));}
main().catch(error=>{console.error(error?.stack||String(error));process.exit(1);});