const lessons=window.F1_LESSONS; const $=s=>document.querySelector(s); let current=lessons[0];
const state=JSON.parse(localStorage.getItem('f1AcademyProgress')||'{}');
const IS_LOCAL=['127.0.0.1','localhost'].includes(location.hostname);
const API_BASE=IS_LOCAL?location.origin:'http://127.0.0.1:8770';
const LOCAL_ACADEMY='http://127.0.0.1:8770/academy/';
function save(){localStorage.setItem('f1AcademyProgress',JSON.stringify(state));renderProgress()}
function renderProgress(){const done=lessons.filter(l=>state[l.id]).length,p=Math.round(done/lessons.length*100);$('#progressBar').style.width=p+'%';$('#progressText').textContent=`${p}% completato • ${done}/${lessons.length} moduli`;document.querySelectorAll('.lessonBtn').forEach(b=>b.classList.toggle('done',!!state[b.dataset.id]))}
function renderNav(){const nav=$('#lessonNav');nav.innerHTML='';lessons.forEach(l=>{const b=document.createElement('button');b.className='lessonBtn';b.dataset.id=l.id;b.textContent=`${l.stage} — ${l.title}`;b.onclick=()=>selectLesson(l.id);nav.appendChild(b)});renderProgress()}
function selectLesson(id){current=lessons.find(x=>x.id===id)||lessons[0];document.querySelectorAll('.lessonBtn').forEach(b=>b.classList.toggle('active',b.dataset.id===id));$('#stage').textContent=current.stage;$('#title').textContent=current.title;$('#objective').textContent=current.objective;$('#script').textContent=current.script;$('#steps').innerHTML=current.steps.map(s=>`<div class="step"><div>${s}</div></div>`).join('');$('#lessonStatus').textContent=state[id]?'COMPLETATO':'NON COMPLETATO';$('#lessonStatus').style.color=state[id]?'#236f55':'';renderQuiz();window.scrollTo({top:0,behavior:'smooth'})}
function renderQuiz(){const q=$('#quiz');if(!current.quiz||!current.quiz.length){$('#quizCard').style.display='none';return}$('#quizCard').style.display='block';q.innerHTML=current.quiz.map((x,i)=>`<div class="quizQ"><strong>${i+1}. ${x[0]}</strong>${x[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}</div>`).join('');$('#quizResult').innerHTML=''}
$('#completeBtn').onclick=()=>{state[current.id]=true;save();$('#lessonStatus').textContent='COMPLETATO';$('#lessonStatus').style.color='#236f55'};
$('#quizBtn').onclick=()=>{let ok=0,total=current.quiz.length;current.quiz.forEach((q,i)=>{const v=document.querySelector(`input[name=q${i}]:checked`);if(v&&+v.value===q[2])ok++});const pass=ok===total;$('#quizResult').innerHTML=`<div class="${pass?'notice':'errorBox'}">${pass?`Test superato: ${ok}/${total}.`:`Test da ripetere: ${ok}/${total}.`}</div>`;if(pass&&current.gate){state[current.id]=true;save();$('#lessonStatus').textContent='COMPLETATO'}};
function speak(){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.script);u.lang='it-IT';u.rate=.98;speechSynthesis.speak(u)} $('#speakBtn').onclick=speak;
async function health(){const box=$('#healthBox');box.textContent='Controllo in corso…';if(!IS_LOCAL){box.innerHTML=`<div class="warn"><b>Modalità pubblica.</b> Per generare i video apri la Academy locale sul PC dove è installato il motore.</div><div class="actions"><button class="btn btnGold" onclick="location.href='${LOCAL_ACADEMY}'">APRI ACADEMY VIDEO LOCALE</button></div>`;return null}try{const r=await fetch(`${API_BASE}/api/health`);if(!r.ok)throw new Error('HTTP '+r.status);const h=await r.json();box.innerHTML=`<div class="ok">Motore locale raggiungibile.</div> Ollama: <b>${h.ollama?'OK':'non attivo'}</b> · Voce: <b>${h.tts_chatterbox?'OK':'non pronta'}</b> · MuseTalk: <b>${h.musetalk?'OK':'non pronto'}</b> · FFmpeg: <b>${h.ffmpeg?'OK':'manca'}</b> · GPU NVIDIA: <b>${h.gpu_nvidia?'sì':'no'}</b>`;if(!h.musetalk&&h.tts_chatterbox&&h.ffmpeg)box.innerHTML+=`<div class="warn">MuseTalk/GPU non disponibile: userò modalità continuità con presenter/B-roll + voce italiana + sottotitoli.</div>`;return h}catch(e){box.innerHTML=`<div class="bad">Motore locale non raggiungibile.</div> Avvia <b>local-media-lab/AVVIA_ACADEMY_UGC.bat</b>.`;return null}}
$('#healthBtn').onclick=health;
$('#ugcBtn').onclick=async()=>{if(!IS_LOCAL){location.href=LOCAL_ACADEMY;return}const h=await health();if(h&&h.tts_chatterbox&&h.ffmpeg)$('#ugcModal').classList.add('show');else $('#healthBox').innerHTML+=`<div class="warn">Il motore non è pronto. Avvia AVVIA_ACADEMY_UGC.bat oppure rilancia INSTALLA_UGC_GRATIS.bat.</div>`};
$('#closeModalBtn').onclick=()=>$('#ugcModal').classList.remove('show');
$('#createUgcBtn').onclick=async()=>{const p=$('#presenter').files[0],v=$('#voice').files[0];if(!p||!v){$('#jobBox').innerHTML='<div class="errorBox">Seleziona presenter e voce di riferimento.</div>';return}const fd=new FormData();fd.append('presenter_video',p);fd.append('voice_reference',v);fd.append('brand','f1');fd.append('objective','spiegazione');fd.append('format','talking');fd.append('topic',current.title);fd.append('script',current.script);[...$('#broll').files].forEach(f=>fd.append('broll',f));$('#jobBox').textContent='Invio al motore locale…';try{const r=await fetch(`${API_BASE}/api/jobs`,{method:'POST',body:fd});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Errore creazione');pollJob(data.job_id)}catch(e){$('#jobBox').innerHTML=`<div class="errorBox">${e.message}. Controlla il motore locale e riprova.</div>`}}
async function pollJob(id){for(let i=0;i<300;i++){await new Promise(r=>setTimeout(r,2000));try{const r=await fetch(`${API_BASE}/api/jobs/${id}`),j=await r.json();$('#jobBox').innerHTML=`<b>${j.message||j.status}</b> — ${j.progress||0}%`;if(j.status==='completed'){const url=`${API_BASE}${j.video_url}`;$('#jobBox').innerHTML=`<div class="ok"><b>Video pronto.</b></div><a class="btn btnGold" href="${url}" target="_blank">APRI VIDEO</a>`;return}if(j.status==='failed'||j.status==='stopped'){throw new Error(j.error||j.message||'Generazione interrotta')}}catch(e){$('#jobBox').innerHTML=`<div class="errorBox">${e.message}</div>`;return}}$('#jobBox').innerHTML='<div class="errorBox">Generazione oltre il tempo previsto. Controlla il motore locale.</div>'}
renderNav();selectLesson('start-here');health();
