const lessons=window.F1_LESSONS;const $=s=>document.querySelector(s);let current=lessons[0];const executed=new Set();const IS_ENGINE=location.port==='8770';const API_BASE=IS_ENGINE?location.origin:'';
function renderProgress(){const n=executed.size,p=Math.round(n/lessons.length*100);$('#progressBar').style.width=p+'%';$('#progressText').textContent=`${n} procedure eseguite in questa sessione`;document.querySelectorAll('.lessonBtn').forEach(b=>b.classList.toggle('done',executed.has(b.dataset.id)))}
function renderNav(){const nav=$('#lessonNav');nav.innerHTML='';lessons.forEach(l=>{const b=document.createElement('button');b.className='lessonBtn';b.dataset.id=l.id;b.innerHTML=`<small>${l.code}</small>${l.title}`;b.onclick=()=>selectLesson(l.id);nav.appendChild(b)});renderProgress()}
function selectLesson(id){current=lessons.find(x=>x.id===id)||lessons[0];document.querySelectorAll('.lessonBtn').forEach(b=>b.classList.toggle('active',b.dataset.id===current.id));$('#stage').textContent=current.stage;$('#title').textContent=current.title;$('#sopCode').textContent=current.code;$('#role').textContent=current.role;$('#trigger').textContent=current.trigger;$('#doneWhen').textContent=current.doneWhen;$('#lessonStatus').textContent='DA ESEGUIRE';$('#lessonStatus').classList.remove('doneStatus');$('#completeBtn').disabled=true;$('#steps').innerHTML=current.commands.map((s,i)=>`<label class="step commandStep"><input type="checkbox" class="cmdCheck" data-i="${i}"><span>${s}</span></label>`).join('');document.querySelectorAll('.cmdCheck').forEach(c=>c.addEventListener('change',checkReady));$('#branches').innerHTML=(current.branches||[]).map(x=>`<div class="branchRow"><strong>SE</strong><span>${x[0]}</span><strong>ALLORA</strong><span>${x[1]}</span></div>`).join('')||'<div class="small">Nessuna eccezione prevista.</div>';$('#recordList').innerHTML=(current.record||[]).map(x=>`<li>${x}</li>`).join('');$('#stopList').innerHTML=(current.stop||[]).map(x=>`<li>${x}</li>`).join('');health(false);window.scrollTo({top:0,behavior:'smooth'})}
function checkReady(){const checks=[...document.querySelectorAll('.cmdCheck')];$('#completeBtn').disabled=!checks.length||!checks.every(c=>c.checked)}
$('#completeBtn').onclick=()=>{executed.add(current.id);$('#lessonStatus').textContent='ESEGUITA';$('#lessonStatus').classList.add('doneStatus');renderProgress()};
$('#nextBtn').onclick=()=>{const next=current.next||lessons[(lessons.indexOf(current)+1)%lessons.length].id;selectLesson(next)};
function speak(){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.script||current.commands.join('. '));u.lang='it-IT';u.rate=1;speechSynthesis.speak(u)}$('#speakBtn').onclick=speak;
async function health(show=true){const box=$('#healthBox');if(!IS_ENGINE){box.innerHTML='<div class="small">La SOP funziona ovunque. La generazione di un nuovo video richiede il motore F1 acceso; i video definitivi verranno incorporati nella guida.</div>';return null}if(show)box.textContent='Controllo motore…';try{const r=await fetch(`${API_BASE}/api/health`);if(!r.ok)throw new Error('HTTP '+r.status);const h=await r.json();box.innerHTML=`<div class="ok">Motore video disponibile.</div> Voce: <b>${h.tts_chatterbox?'OK':'NO'}</b> · FFmpeg: <b>${h.ffmpeg?'OK':'NO'}</b> · Lip-sync: <b>${h.musetalk?'OK':'modalità continuità'}</b>`;return h}catch(e){box.innerHTML='<div class="bad">Motore video non disponibile. La SOP resta comunque eseguibile.</div>';return null}}
$('#ugcBtn').onclick=async()=>{if(!IS_ENGINE){$('#healthBox').innerHTML='<div class="warn">Da questa pagina remota puoi eseguire la SOP. Per creare un nuovo video serve il motore F1 acceso. Il funzionario non deve fermare il lavoro per questo.</div>';return}const h=await health();if(h&&h.tts_chatterbox&&h.ffmpeg)$('#ugcModal').classList.add('show')};
$('#closeModalBtn').onclick=()=>$('#ugcModal').classList.remove('show');
$('#createUgcBtn').onclick=async()=>{const p=$('#presenter').files[0],v=$('#voice').files[0];if(!p||!v){$('#jobBox').innerHTML='<div class="errorBox">Seleziona presenter e voce.</div>';return}const fd=new FormData();fd.append('presenter_video',p);fd.append('voice_reference',v);fd.append('brand','f1');fd.append('objective','spiegazione');fd.append('format','talking');fd.append('topic',`${current.code} ${current.title}`);fd.append('script',current.script||current.commands.join('. '));[...$('#broll').files].forEach(f=>fd.append('broll',f));$('#jobBox').textContent='Creazione video SOP…';try{const r=await fetch(`${API_BASE}/api/jobs`,{method:'POST',body:fd});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Errore');pollJob(data.job_id)}catch(e){$('#jobBox').innerHTML=`<div class="errorBox">${e.message}</div>`}}
async function pollJob(id){for(let i=0;i<300;i++){await new Promise(r=>setTimeout(r,2000));try{const r=await fetch(`${API_BASE}/api/jobs/${id}`),j=await r.json();$('#jobBox').innerHTML=`<b>${j.message||j.status}</b> — ${j.progress||0}%`;if(j.status==='completed'){const url=`${API_BASE}${j.video_url}`;$('#jobBox').innerHTML=`<div class="ok"><b>Video SOP pronto.</b></div><a class="btn btnGold" href="${url}" target="_blank">APRI VIDEO</a>`;return}if(j.status==='failed'||j.status==='stopped')throw new Error(j.error||j.message)}catch(e){$('#jobBox').innerHTML=`<div class="errorBox">${e.message}</div>`;return}}}
renderNav();selectLesson('start-shift');