const lessons=window.F1_LESSONS;const $=s=>document.querySelector(s);let current=lessons[0];const executed=new Set();const IS_ENGINE=location.port==='8770';const API_BASE=IS_ENGINE?location.origin:'';let commandIndex=0;let commandDone=[];
const codeMap=Object.fromEntries(lessons.map(l=>[l.code,l.id]));
const mission=()=>JSON.parse(localStorage.getItem('f1TodayMission')||'null');
function renderProgress(){const n=executed.size,p=Math.round(n/lessons.length*100);$('#progressBar').style.width=p+'%';$('#progressText').textContent=`${n} procedure eseguite in questa sessione`;document.querySelectorAll('.lessonBtn').forEach(b=>b.classList.toggle('done',executed.has(b.dataset.id)))}
function renderNav(){const nav=$('#lessonNav');nav.innerHTML='';lessons.forEach(l=>{const b=document.createElement('button');b.className='lessonBtn';b.dataset.id=l.id;b.innerHTML=`<small>${l.code}</small>${l.title}`;b.onclick=()=>selectLesson(l.id);nav.appendChild(b)});renderProgress()}
function selectLesson(id){current=lessons.find(x=>x.id===id)||lessons[0];commandIndex=0;commandDone=current.commands.map(()=>false);document.querySelectorAll('.lessonBtn').forEach(b=>b.classList.toggle('active',b.dataset.id===current.id));$('#stage').textContent=current.stage;$('#title').textContent=current.title;$('#sopCode').textContent=current.code;$('#role').textContent=current.role;$('#trigger').textContent=current.trigger;$('#doneWhen').textContent=current.doneWhen;$('#lessonStatus').textContent='DA ESEGUIRE';$('#lessonStatus').classList.remove('doneStatus');renderCommands();renderBranches();$('#recordList').innerHTML=(current.record||[]).map(x=>`<li>${x}</li>`).join('');$('#stopList').innerHTML=(current.stop||[]).map(x=>`<li>${x}</li>`).join('');health(false);window.scrollTo({top:0,behavior:'smooth'})}
function renderCommands(){const box=$('#steps');box.innerHTML=current.commands.map((s,i)=>{const active=i===commandIndex,done=commandDone[i];return `<button class="commandAction ${active?'activeCommand':''} ${done?'doneCommand':''}" data-i="${i}" ${(!active||done)?'disabled':''}><span class="commandNo">${String(i+1).padStart(2,'0')}</span><span class="commandText">${s}</span><span class="commandGo">${done?'✓':'→'}</span></button>`}).join('');box.querySelectorAll('.commandAction').forEach(b=>b.onclick=()=>executeCommand(+b.dataset.i));$('#completeBtn').disabled=!commandDone.every(Boolean)}
function renderBranches(){const rows=current.branches||[];$('#branches').innerHTML=rows.length?rows.map((x,i)=>`<button class="branchAction" data-b="${i}"><span><b>SE</b>${x[0]}</span><span><b>ALLORA</b>${x[1]}</span></button>`).join(''):'<div class="small">Nessuna eccezione prevista.</div>';document.querySelectorAll('.branchAction').forEach(b=>b.onclick=()=>executeBranch(+b.dataset.b))}
function findTarget(text){const m=text.match(/F1-OG-\d{3}/);return m&&codeMap[m[0]]?codeMap[m[0]]:null}
function finishCommand(i){commandDone[i]=true;if(i<current.commands.length-1){commandIndex=i+1;renderCommands();document.querySelector('.activeCommand')?.scrollIntoView({behavior:'smooth',block:'center'})}else{commandIndex=i;renderCommands();executed.add(current.id);$('#lessonStatus').textContent='ESEGUITA';$('#lessonStatus').classList.add('doneStatus');renderProgress();setTimeout(()=>{const next=current.next;if(next&&next!==current.id)selectLesson(next)},500)}}
function executeCommand(i){const text=current.commands[i];const target=findTarget(text);if(/TODAY[’']S MISSION/i.test(text)){openMission(()=>finishCommand(i));return}if(target){finishCommand(i);setTimeout(()=>selectLesson(target),180);return}if(/AVVIA MISSIONE/i.test(text)){finishCommand(i);return}openAction(text,()=>finishCommand(i))}
function executeBranch(i){const [condition,result]=current.branches[i];const target=findTarget(result);openDirective(condition,result,()=>{if(target)selectLesson(target)})}
function ensureOverlay(){let o=document.querySelector('#actionOverlay');if(o)return o;o=document.createElement('div');o.id='actionOverlay';o.className='actionOverlay';document.body.appendChild(o);return o}
function openAction(text,onDone){const o=ensureOverlay();o.innerHTML=`<div class="actionSheet"><div class="eyebrow">COMANDO</div><h2>${text}</h2><button class="btn btnGold bigAction" id="confirmAction">ESEGUITO</button><button class="btn btnSoft" id="cancelAction">INDIETRO</button></div>`;o.classList.add('show');$('#confirmAction').onclick=()=>{o.classList.remove('show');onDone()};$('#cancelAction').onclick=()=>o.classList.remove('show')}
function openDirective(condition,result,after){const o=ensureOverlay();o.innerHTML=`<div class="actionSheet"><div class="eyebrow">SE</div><h2>${condition}</h2><div class="directive">${result}</div><button class="btn btnGold bigAction" id="doDirective">ESEGUI</button><button class="btn btnSoft" id="cancelDirective">INDIETRO</button></div>`;o.classList.add('show');$('#doDirective').onclick=()=>{o.classList.remove('show');after&&after()};$('#cancelDirective').onclick=()=>o.classList.remove('show')}
function openMission(onDone){const o=ensureOverlay();const m=mission();if(!m){o.innerHTML=`<div class="actionSheet"><div class="eyebrow">TODAY’S MISSION</div><h2>MISSIONE NON ASSEGNATA</h2><div class="directive">STOP. Il funzionario non sceglie da solo zona o attività. Il responsabile deve assegnare la missione.</div><button class="btn btnSoft" id="closeMission">CHIUDI</button></div>`;o.classList.add('show');$('#closeMission').onclick=()=>o.classList.remove('show');return}o.innerHTML=`<div class="actionSheet"><div class="eyebrow">TODAY’S MISSION</div><h2>${m.comune||'—'} · ${m.microzona||'—'}</h2><div class="missionGrid"><div><span>VIA</span><strong>${m.via||'—'}</strong></div><div><span>CIVICI</span><strong>${m.civici||'—'}</strong></div><div><span>OBIETTIVO</span><strong>${m.obiettivo||'—'}</strong></div><div><span>FOLLOW-UP</span><strong>${m.followup||'NESSUNO'}</strong></div></div><button class="btn btnGold bigAction" id="missionRead">MISSIONE LETTA</button><button class="btn btnSoft" id="closeMission">INDIETRO</button></div>`;o.classList.add('show');$('#missionRead').onclick=()=>{o.classList.remove('show');onDone()};$('#closeMission').onclick=()=>o.classList.remove('show')}
$('#completeBtn').onclick=()=>{if(commandDone.every(Boolean)){executed.add(current.id);renderProgress();const next=current.next||lessons[(lessons.indexOf(current)+1)%lessons.length].id;selectLesson(next)}};
$('#nextBtn').onclick=()=>{const next=current.next||lessons[(lessons.indexOf(current)+1)%lessons.length].id;selectLesson(next)};
function speak(){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.script||current.commands.join('. '));u.lang='it-IT';u.rate=1;speechSynthesis.speak(u)}$('#speakBtn').onclick=speak;
async function health(show=true){const box=$('#healthBox');if(!IS_ENGINE){box.innerHTML='<div class="small">La SOP funziona ovunque. La generazione di un nuovo video richiede il motore F1 acceso.</div>';return null}if(show)box.textContent='Controllo motore…';try{const r=await fetch(`${API_BASE}/api/health`);if(!r.ok)throw new Error('HTTP '+r.status);const h=await r.json();box.innerHTML=`<div class="ok">Motore video disponibile.</div> Voce: <b>${h.tts_chatterbox?'OK':'NO'}</b> · FFmpeg: <b>${h.ffmpeg?'OK':'NO'}</b> · Lip-sync: <b>${h.musetalk?'OK':'modalità continuità'}</b>`;return h}catch(e){box.innerHTML='<div class="bad">Motore video non disponibile. La SOP resta comunque eseguibile.</div>';return null}}
$('#ugcBtn').onclick=async()=>{if(!IS_ENGINE){$('#healthBox').innerHTML='<div class="warn">Per creare un nuovo video serve il motore F1 acceso.</div>';return}const h=await health();if(h&&h.tts_chatterbox&&h.ffmpeg)$('#ugcModal').classList.add('show')};$('#closeModalBtn').onclick=()=>$('#ugcModal').classList.remove('show');
$('#createUgcBtn').onclick=async()=>{const p=$('#presenter').files[0],v=$('#voice').files[0];if(!p||!v){$('#jobBox').innerHTML='<div class="errorBox">Seleziona presenter e voce.</div>';return}const fd=new FormData();fd.append('presenter_video',p);fd.append('voice_reference',v);fd.append('brand','f1');fd.append('objective','spiegazione');fd.append('format','talking');fd.append('topic',`${current.code} ${current.title}`);fd.append('script',current.script||current.commands.join('. '));[...$('#broll').files].forEach(f=>fd.append('broll',f));$('#jobBox').textContent='Creazione video SOP…';try{const r=await fetch(`${API_BASE}/api/jobs`,{method:'POST',body:fd});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Errore');pollJob(data.job_id)}catch(e){$('#jobBox').innerHTML=`<div class="errorBox">${e.message}</div>`}}
async function pollJob(id){for(let i=0;i<300;i++){await new Promise(r=>setTimeout(r,2000));try{const r=await fetch(`${API_BASE}/api/jobs/${id}`),j=await r.json();$('#jobBox').innerHTML=`<b>${j.message||j.status}</b> — ${j.progress||0}%`;if(j.status==='completed'){const url=`${API_BASE}${j.video_url}`;$('#jobBox').innerHTML=`<div class="ok"><b>Video SOP pronto.</b></div><a class="btn btnGold" href="${url}" target="_blank">APRI VIDEO</a>`;return}if(j.status==='failed'||j.status==='stopped')throw new Error(j.error||j.message)}catch(e){$('#jobBox').innerHTML=`<div class="errorBox">${e.message}</div>`;return}}}
renderNav();selectLesson('start-shift');