#!/usr/bin/env python3
"""Publish only approved F1 institutional preview assets through Buffer.

Production source of truth:
- publisher/social-preview-latest.json
- legacy_hidden must be true
- required_visual_compliance must be F1_LIGHT_INSTITUTIONAL_V2
- entry publication_ready must be true
- entry visual_compliance must be F1_LIGHT_INSTITUTIONAL_V2

The publisher deliberately does NOT rebuild graphics. It publishes the exact JPG
that was already generated by the institutional renderer and shown in
monday-control.html.
"""
from __future__ import annotations

import argparse
import json
import os
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any

import requests

import buffer_twice_daily as base

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "publisher" / "social-preview-latest.json"
QUEUE_PATH = ROOT / "publisher" / "queue.json"
MEDIA_DIR = ROOT / "publisher" / "media" / "generated" / "buffer-production"
COMPLIANCE = "F1_LIGHT_INSTITUTIONAL_V2"


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def normalize_cloudinary_url(raw: str) -> str:
    value = str(raw or "").strip().strip('"').strip("'")
    if value.startswith("CLOUDINARY_URL="):
        value = value.split("=", 1)[1].strip().strip('"').strip("'")
    return value


def instagram_post_metadata(service: str, job: dict[str, Any]) -> str:
    # These production assets are single static JPG posts, not carousels.
    if service == "facebook":
        return "{ facebook: { type: post } }"
    if service == "instagram":
        return "{ instagram: { type: post, shouldShareToFeed: true } }"
    return ""


def validate_manifest(manifest: dict[str, Any], day: date) -> list[dict[str, Any]]:
    if manifest.get("pipeline") != "social-preview-latest":
        raise base.BufferAutomationError("Unexpected preview manifest pipeline")
    if manifest.get("legacy_hidden") is not True:
        raise base.BufferAutomationError("Legacy preview assets are not hidden; production blocked")
    if manifest.get("required_visual_compliance") != COMPLIANCE:
        raise base.BufferAutomationError("Manifest is not bound to the institutional F1 renderer")

    rows: list[dict[str, Any]] = []
    for entry in manifest.get("entries") or []:
        if str(entry.get("content_date") or "") != day.isoformat():
            continue
        if entry.get("publication_ready") is not True:
            continue
        if entry.get("visual_compliance") != COMPLIANCE:
            continue
        if entry.get("brand_template") != "light_f1_institutional":
            continue
        if not str(entry.get("caption") or "").strip():
            continue
        if not str(entry.get("asset_url") or "").startswith("https://"):
            continue
        # Service 3 remains blocked unless a future verified-today flag is present.
        if entry.get("service_id") == "service_3_bonus_casa" and entry.get("official_verified_today") is not True:
            continue
        rows.append(dict(entry))

    if not rows:
        raise base.BufferAutomationError(
            f"No production-ready institutional F1 previews found for {day.isoformat()}"
        )
    rows.sort(key=lambda x: (str(x.get("scheduled_at") or ""), str(x.get("id") or "")))
    return rows


def choose_entry(entries: list[dict[str, Any]], day: date, slot: str) -> dict[str, Any]:
    # Two established daily F1 slots. Rotate through the approved candidates so
    # Agent Pricing, Piano di Vendita and Recruiting all enter production over time.
    slot_offset = 0 if slot == "morning" else 1
    index = (day.toordinal() * 2 + slot_offset) % len(entries)
    return entries[index]


def download_asset(entry: dict[str, Any], day: date, slot: str) -> Path:
    MEDIA_DIR.mkdir(parents=True, exist_ok=True)
    safe_id = "".join(c if c.isalnum() or c in "-_" else "-" for c in str(entry.get("id") or "f1"))
    path = MEDIA_DIR / f"{day.isoformat()}-{slot}-{safe_id}.jpg"
    response = requests.get(
        str(entry["asset_url"]),
        headers={"User-Agent": "F1-Immobiliare-Production-Publisher/1.0"},
        timeout=120,
        allow_redirects=True,
    )
    response.raise_for_status()
    content_type = str(response.headers.get("content-type") or "").lower()
    if "image" not in content_type and len(response.content) < 20_000:
        raise base.BufferAutomationError(
            f"Preview asset download does not look like a valid image: {content_type}"
        )
    path.write_bytes(response.content)
    if path.stat().st_size < 20_000:
        raise base.BufferAutomationError("Downloaded institutional preview is unexpectedly small")
    return path


def build_job(entry: dict[str, Any], day: date, slot: str, path: Path) -> dict[str, Any]:
    return {
        "id": f"f1-production-{day.isoformat()}-{slot}-{entry.get('id')}",
        "client_id": "f1-immobiliare",
        "created_by": "buffer-preview-production",
        "source_preview_id": entry.get("id"),
        "source_preview_run_id": entry.get("source_run_id"),
        "service_id": entry.get("service_id"),
        "title": entry.get("title"),
        "caption": entry.get("caption"),
        "cta": entry.get("cta"),
        "hashtags": entry.get("hashtags") or [],
        "territory": entry.get("territory"),
        "brand_template": "light_f1_institutional",
        "visual_compliance": COMPLIANCE,
        "format": "photo",
        "media": str(path.relative_to(ROOT)),
        "scheduled_at": base.due_datetime(day, slot).isoformat(),
        "platforms": [
            {"platform": service, "integration_id": "buffer"}
            for service in base.TARGET_SERVICES
        ],
        "status": "buffer_pending",
        "buffer_posts": [],
        "buffer_scheduled_platforms": [],
        "approval_required": False,
        "manual_approval_required": False,
        "autonomous_publish": True,
        "production_source": "social-preview-latest.json",
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--slot", choices=["auto", "morning", "evening"], default="auto")
    parser.add_argument("--date", help="Europe/Rome date YYYY-MM-DD; default today")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    now = datetime.now(base.ROME)
    slot = base.pick_slot(now, args.slot)
    if slot is None:
        print(f"NOOP: no F1 production slot is due at {now.isoformat(timespec='minutes')}")
        return 0

    day = base.target_date(args.date, now)
    if args.slot == "auto" and day != now.date():
        print("NOOP: automatic production scheduler only handles today's Rome date")
        return 0

    manifest = load_json(MANIFEST_PATH, {})
    entries = validate_manifest(manifest, day)
    entry = choose_entry(entries, day, slot)

    queue = load_json(QUEUE_PATH, {"version": 6, "jobs": []})
    queue.setdefault("jobs", [])

    expected_id = f"f1-production-{day.isoformat()}-{slot}-{entry.get('id')}"
    existing = base.find_job(queue, expected_id)
    if existing:
        scheduled = set(str(x) for x in existing.get("buffer_scheduled_platforms", []))
        if set(base.TARGET_SERVICES).issubset(scheduled):
            print(f"NOOP: {expected_id} already scheduled in Buffer for all 3 channels")
            return 0

    path: Path | None = None
    try:
        path = download_asset(entry, day, slot)
        template = build_job(entry, day, slot, path)
        if existing:
            preserved = {
                "buffer_posts": list(existing.get("buffer_posts", [])),
                "buffer_scheduled_platforms": list(existing.get("buffer_scheduled_platforms", [])),
                "cloudinary_assets": list(existing.get("cloudinary_assets", [])),
            }
            existing.clear()
            existing.update(template)
            existing.update(preserved)
            job = existing
        else:
            queue["jobs"].append(template)
            job = template

        api_key = os.getenv("BUFFER_API_KEY", "").strip()
        cloudinary_url = normalize_cloudinary_url(os.getenv("CLOUDINARY_URL", ""))
        missing = [name for name, value in (("BUFFER_API_KEY", api_key), ("CLOUDINARY_URL", cloudinary_url)) if not value]
        if missing:
            raise base.BufferAutomationError("Missing GitHub Actions Secrets: " + ", ".join(missing))

        organization_id, channels = base.discover_buffer_channels(api_key)
        job["buffer_organization_id"] = organization_id
        job["buffer_channels"] = channels

        # Correct Buffer metadata for one-image Instagram feed posts.
        base.gql_metadata = instagram_post_metadata
        hosted = base.ensure_cloudinary_assets(job, cloudinary_url)
        base.persist_queue(queue)

        if args.dry_run:
            job["status"] = "buffer_dry_run_ok"
            base.persist_queue(queue)
            print(json.dumps({
                "job_id": job["id"],
                "status": job["status"],
                "slot": slot,
                "preview": entry.get("asset_url"),
                "channels": channels,
                "cloudinary": [x.get("url") for x in hosted],
            }, ensure_ascii=False, indent=2))
            return 0

        scheduled = set(str(x) for x in job.get("buffer_scheduled_platforms", []))
        results: list[dict[str, Any]] = []
        for service in base.TARGET_SERVICES:
            if service in scheduled:
                continue
            channel = channels[service]
            try:
                result = base.create_buffer_post(
                    api_key,
                    str(channel["id"]),
                    service,
                    job,
                    hosted,
                    datetime.now(base.ROME),
                )
                job.setdefault("buffer_posts", []).append(result)
                job.setdefault("buffer_scheduled_platforms", []).append(service)
                scheduled.add(service)
                results.append({**result, "status": "scheduled"})
                base.persist_queue(queue)
            except Exception as exc:
                results.append({"service": service, "status": "error", "error": str(exc)})

        if set(base.TARGET_SERVICES).issubset(scheduled):
            job["status"] = "scheduled_in_buffer"
            job.pop("blocked_reason", None)
            code = 0
        elif scheduled:
            job["status"] = "buffer_partially_scheduled"
            job["blocked_reason"] = "Buffer retry required for remaining channels"
            code = 1
        else:
            job["status"] = "buffer_retry_required"
            job["blocked_reason"] = "Buffer did not schedule any target channel"
            code = 1

        base.persist_queue(queue)
        print(json.dumps({
            "job_id": job["id"],
            "slot": slot,
            "source_preview_id": entry.get("id"),
            "service_id": entry.get("service_id"),
            "status": job["status"],
            "results": results,
        }, ensure_ascii=False, indent=2))
        return code
    except Exception as exc:
        print(json.dumps({"status": "production_blocked", "error": str(exc)}, ensure_ascii=False, indent=2))
        return 1
    finally:
        if path and path.exists():
            try:
                path.unlink()
            except OSError:
                pass


if __name__ == "__main__":
    raise SystemExit(main())
