#!/usr/bin/env python3
"""Photo-first automatic social publisher compatibility layer.

Purpose:
- publish static-photo jobs generated by the 4-folder pipeline;
- support Instagram single-image publishing correctly;
- upload the image to LinkedIn before creating the post;
- allow available platforms to publish even if another platform is missing secrets;
- keep TikTok and YouTube out of the current photo-only cycle.

The core queue/status logic remains in direct_api_publish.py.
"""
from __future__ import annotations

import mimetypes
import os
from pathlib import Path
from typing import Any

import requests

import direct_api_publish as core


def instagram_photo_publish(
    job: dict[str, Any],
    client: dict[str, Any],
    paths: list[Path],
    cache: core.PublicMediaCache,
) -> dict[str, Any]:
    token = core.secret(client, "INSTAGRAM_ACCESS_TOKEN")
    ig_user_id = core.secret(client, "INSTAGRAM_USER_ID")
    urls = [cache.upload(path, str(job["id"]), idx) for idx, path in enumerate(paths, 1)]

    if len(urls) == 1:
        created = core.request(
            "POST",
            f"{core.meta_graph_base()}/{ig_user_id}/media",
            params={
                "image_url": urls[0],
                "caption": str(job.get("caption") or "")[:2200],
                "access_token": token,
            },
        ).json()
        container_id = str(created["id"])
        core.ig_wait_container(container_id, token)
        published = core.request(
            "POST",
            f"{core.meta_graph_base()}/{ig_user_id}/media_publish",
            params={"creation_id": container_id, "access_token": token},
        ).json()
        return {
            "container_id": container_id,
            "media_id": published.get("id"),
            "mode": "single-image",
        }

    if len(urls) < 2:
        raise core.PublishError("Instagram photo publishing requires at least one image")

    children: list[str] = []
    for url in urls[:10]:
        child = core.request(
            "POST",
            f"{core.meta_graph_base()}/{ig_user_id}/media",
            params={
                "image_url": url,
                "is_carousel_item": "true",
                "access_token": token,
            },
        ).json()
        child_id = str(child["id"])
        core.ig_wait_container(child_id, token)
        children.append(child_id)

    parent = core.request(
        "POST",
        f"{core.meta_graph_base()}/{ig_user_id}/media",
        params={
            "caption": str(job.get("caption") or "")[:2200],
            "media_type": "CAROUSEL",
            "children": ",".join(children),
            "access_token": token,
        },
    ).json()
    container_id = str(parent["id"])
    core.ig_wait_container(container_id, token)
    published = core.request(
        "POST",
        f"{core.meta_graph_base()}/{ig_user_id}/media_publish",
        params={"creation_id": container_id, "access_token": token},
    ).json()
    return {
        "container_id": container_id,
        "media_id": published.get("id"),
        "children": children,
        "mode": "carousel",
    }


def linkedin_photo_publish(
    job: dict[str, Any],
    client: dict[str, Any],
    paths: list[Path],
    _cache: core.PublicMediaCache,
) -> dict[str, Any]:
    if not paths:
        raise core.PublishError("LinkedIn photo post has no image")

    token = core.secret(client, "LINKEDIN_ACCESS_TOKEN")
    author = core.secret(client, "LINKEDIN_AUTHOR_URN")
    version = os.getenv("LINKEDIN_VERSION", "202606").strip()
    headers = {
        "Authorization": f"Bearer {token}",
        "X-Restli-Protocol-Version": "2.0.0",
        "Linkedin-Version": version,
        "Content-Type": "application/json",
    }

    init = core.request(
        "POST",
        "https://api.linkedin.com/rest/images?action=initializeUpload",
        headers=headers,
        json={"initializeUploadRequest": {"owner": author}},
    ).json()
    value = init.get("value") or {}
    upload_url = str(value.get("uploadUrl") or "")
    image_urn = str(value.get("image") or "")
    if not upload_url or not image_urn:
        raise core.PublishError(f"LinkedIn image initializeUpload response incomplete: {init}")

    path = paths[0]
    ctype = mimetypes.guess_type(path.name)[0] or "image/jpeg"
    response = requests.put(
        upload_url,
        headers={"Authorization": f"Bearer {token}", "Content-Type": ctype},
        data=path.read_bytes(),
        timeout=300,
    )
    if not response.ok:
        raise core.PublishError(
            f"LinkedIn image upload -> {response.status_code}: {response.text[:1000]}"
        )

    post = core.request(
        "POST",
        "https://api.linkedin.com/rest/posts",
        headers=headers,
        json={
            "author": author,
            "commentary": str(job.get("caption") or "")[:3000],
            "visibility": "PUBLIC",
            "distribution": {
                "feedDistribution": "MAIN_FEED",
                "targetEntities": [],
                "thirdPartyDistributionChannels": [],
            },
            "content": {
                "media": {
                    "id": image_urn,
                    "altText": str(job.get("title") or job.get("client_name") or "")[:300],
                }
            },
            "lifecycleState": "PUBLISHED",
            "isReshareDisabledByAuthor": False,
        },
    )
    return {
        "post_id": post.headers.get("x-restli-id", ""),
        "image_urn": image_urn,
        "mode": "single-image",
    }


def publish_job_resilient(
    job: dict[str, Any], only: set[str] | None, dry_run: bool
) -> tuple[list[dict[str, Any]], bool]:
    client = core.client_config(str(job["client_id"]))
    paths = core.media_paths(job)
    platforms = core.remaining_platforms(job, only)
    results: list[dict[str, Any]] = []
    if not platforms:
        return results, True

    cache = core.PublicMediaCache()
    any_failure = False
    try:
        for platform in platforms:
            missing = core.required_secrets(platform, client)
            if missing:
                results.append({"platform": platform, "status": "blocked", "missing": missing})
                any_failure = True
                continue

            if dry_run:
                results.append({"platform": platform, "status": "ready"})
                continue

            publisher = core.PUBLISHERS.get(platform)
            if not publisher:
                results.append({"platform": platform, "status": "unsupported"})
                any_failure = True
                continue

            try:
                payload = publisher(job, client, paths, cache)
                results.append({"platform": platform, "status": "published", "result": payload})
                published = set(str(x) for x in job.get("published_platforms", []))
                published.add(platform)
                job["published_platforms"] = sorted(published)
            except Exception as exc:
                results.append({"platform": platform, "status": "error", "error": str(exc)})
                any_failure = True
    finally:
        cache.cleanup()

    if not dry_run:
        expected = set(core.job_platforms(job))
        done = set(str(x) for x in job.get("published_platforms", []))
        if expected and expected.issubset(done):
            job["status"] = "published"
            job.pop("blocked_reason", None)
        elif done:
            job["status"] = "partially_published"
        else:
            job["status"] = "ready"

    return results, not any_failure


def main() -> int:
    os.environ.setdefault("LINKEDIN_VERSION", "202606")
    core.PUBLISHERS["instagram"] = instagram_photo_publish
    core.PUBLISHERS["linkedin"] = linkedin_photo_publish
    core.PUBLISHERS["linkedin-page"] = linkedin_photo_publish
    core.publish_job = publish_job_resilient
    return core.main()


if __name__ == "__main__":
    raise SystemExit(main())
