-- F1 Content Hub multi-client bridge schema
-- Applied to Supabase project nqnmlsmeiynxbdojeyjt on 2026-09-24.
-- This file is the repository reference for the additive production changes.

alter table public.f1_content_clients
  add column if not exists timezone text not null default 'Europe/Rome',
  add column if not exists auto_publish boolean not null default false,
  add column if not exists approval_required boolean not null default true,
  add column if not exists automation_status text not null default 'CONFIGURAZIONE INCOMPLETA',
  add column if not exists last_website_sync_at timestamptz;

alter table public.f1_content_calendar
  add column if not exists queue_job_id text,
  add column if not exists provider text,
  add column if not exists external_post_id text,
  add column if not exists external_url text,
  add column if not exists last_checked_at timestamptz,
  add column if not exists retry_count integer not null default 0,
  add column if not exists error text;

create unique index if not exists f1_content_calendar_queue_job_uidx
  on public.f1_content_calendar(queue_job_id) where queue_job_id is not null;
create index if not exists f1_content_calendar_client_id_idx on public.f1_content_calendar(client_id);
create index if not exists f1_content_calendar_content_id_idx on public.f1_content_calendar(content_id);
create index if not exists f1_content_calendar_publication_at_idx on public.f1_content_calendar(publication_at);
create index if not exists f1_content_items_client_id_idx on public.f1_content_items(client_id);
create index if not exists f1_content_media_client_id_idx on public.f1_content_media(client_id);
create index if not exists f1_content_media_content_id_idx on public.f1_content_media(content_id);
create index if not exists f1_content_properties_client_id_idx on public.f1_content_properties(client_id);

alter table public.f1_content_items drop constraint if exists f1_content_items_status_check;
alter table public.f1_content_items add constraint f1_content_items_status_check check (
  status = any(array[
    'IN ARRIVO','DA CLASSIFICARE','DA LAVORARE','IN LAVORAZIONE','PRONTO',
    'DA APPROVARE','APPROVATO','PROGRAMMATO','IN PUBBLICAZIONE','PUBBLICATO','ARCHIVIATO',
    'ERRORE_MEDIA','ERRORE_QUEUE','ERRORE_PUBBLICAZIONE','CANALE_DA_COLLEGARE','CREDENZIALI_MANCANTI'
  ]::text[])
);

create table if not exists public.f1_client_social_channels (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references public.f1_content_clients(id) on delete cascade,
  platform text not null,
  provider text not null default 'direct',
  external_channel_id text,
  secret_prefix text,
  enabled boolean not null default false,
  verified boolean not null default false,
  connection_status text not null default 'CANALE_DA_COLLEGARE',
  last_verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_id, client_id, platform)
);

create table if not exists public.f1_client_web_sources (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references public.f1_content_clients(id) on delete cascade,
  url text not null,
  canonical_url text not null,
  page_type text not null default 'PAGE',
  title text not null default '',
  description text not null default '',
  image_url text,
  content_hash text,
  discovered_at timestamptz not null default now(),
  last_checked_at timestamptz not null default now(),
  active boolean not null default true,
  unique(owner_id, client_id, canonical_url)
);

create table if not exists public.f1_publication_events (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid references public.f1_content_clients(id) on delete set null,
  content_id uuid references public.f1_content_items(id) on delete set null,
  calendar_id uuid references public.f1_content_calendar(id) on delete set null,
  queue_job_id text,
  provider text,
  platform text,
  action text not null,
  status text not null,
  external_id text,
  retry_count integer not null default 0,
  error text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.f1_client_store_cycles (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references public.f1_content_clients(id) on delete cascade,
  provider text not null default 'DA_CONFIGURARE',
  store_created_at timestamptz not null default now(),
  clone_review_due_at timestamptz not null default (now() + interval '75 days'),
  clone_status text not null default 'ATTIVO',
  clone_source_store_id text,
  clone_target_store_id text,
  provider_cost numeric,
  renewal_date date,
  cost_notes text not null default '',
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_id, client_id, provider)
);

create index if not exists f1_client_social_channels_client_idx on public.f1_client_social_channels(client_id);
create index if not exists f1_client_web_sources_client_idx on public.f1_client_web_sources(client_id);
create index if not exists f1_client_web_sources_checked_idx on public.f1_client_web_sources(last_checked_at);
create index if not exists f1_publication_events_calendar_idx on public.f1_publication_events(calendar_id);
create index if not exists f1_publication_events_client_created_idx on public.f1_publication_events(client_id, created_at desc);
create index if not exists f1_client_store_cycles_due_idx on public.f1_client_store_cycles(clone_review_due_at);
create index if not exists f1_client_store_cycles_client_idx on public.f1_client_store_cycles(client_id);
create index if not exists f1_publication_events_owner_idx on public.f1_publication_events(owner_id);
create index if not exists f1_publication_events_content_idx on public.f1_publication_events(content_id);

alter table public.f1_client_social_channels enable row level security;
alter table public.f1_client_web_sources enable row level security;
alter table public.f1_publication_events enable row level security;
alter table public.f1_client_store_cycles enable row level security;

drop policy if exists "owners_manage_social_channels" on public.f1_client_social_channels;
create policy "owners_manage_social_channels" on public.f1_client_social_channels
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

drop policy if exists "owners_manage_web_sources" on public.f1_client_web_sources;
create policy "owners_manage_web_sources" on public.f1_client_web_sources
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

drop policy if exists "owners_manage_publication_events" on public.f1_publication_events;
create policy "owners_manage_publication_events" on public.f1_publication_events
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

drop policy if exists "owners_manage_store_cycles" on public.f1_client_store_cycles;
create policy "owners_manage_store_cycles" on public.f1_client_store_cycles
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

grant select, insert, update, delete on table public.f1_client_social_channels to authenticated;
grant select, insert, update, delete on table public.f1_client_web_sources to authenticated;
grant select, insert, update, delete on table public.f1_publication_events to authenticated;
grant select, insert, update, delete on table public.f1_client_store_cycles to authenticated;
grant usage, select on sequence public.f1_publication_events_id_seq to authenticated;
